#!/usr/bin/env python3
# Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
"""Generate ggml-metal-bposit8.h: det_soft.h + bp8_exact_soft.h (portable C == MSL) + the
constant code tables + the two Metal kernels. Self-contained (no #include) so the Metal
library embedder can inline it with one sed step, like ggml-common.h."""
import os, struct, sys
HERE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'ggml-det')   # det_soft.h, bp8_exact_soft.h, det_soft_ops.h
def body(fn):
    s = open(os.path.join(HERE, fn)).read()
    return s.replace('#include "det_soft.h"\n', '')
BP8_ES, ZERO, NAR = 2, 0x00, 0x80
def code_to_ME(p):
    if p in (ZERO, NAR): return 0, 0
    s = (p >> 7) & 1; rest = p & 0x7F
    if s: rest = ((~rest) + 1) & 0x7F
    leading = (rest >> 6) & 1; rs = 0
    while rs < 7 and ((rest >> (6 - rs)) & 1) == leading: rs += 1
    e = fb = fw = 0
    if rs == 7: k = 6 if leading else -7
    else:
        k = (rs - 1) if leading else -rs
        rem = 7 - (rs + 1); r2 = rest & ((1 << rem) - 1); ew = min(BP8_ES, rem)
        if ew > 0: e = ((r2 >> (rem - ew)) & ((1 << ew) - 1)) << (BP8_ES - ew)
        rem -= ew; fw = rem; fb = r2 & ((1 << fw) - 1) if fw > 0 else 0
    m = (1 << fw) + fb
    return (-m if s else m), 4 * k + e - fw
def dbits(M, E):
    v = M * 2.0 ** E  # exact: small M, moderate E
    return struct.unpack('<Q', struct.pack('<d', v))[0]
tM, tE = zip(*[code_to_ME(c) for c in range(256)])
codes = sorted((c for c in range(256) if c != NAR), key=lambda c: tM[c] * 2.0 ** tE[c])
sv = [dbits(tM[c], tE[c]) for c in codes]
assert len(set(sv)) == 255
def carr(t, name, vals, fmt):
    rows = [', '.join(fmt(v) for v in vals[i:i+8]) for i in range(0, len(vals), 8)]
    return f"constant {t} {name}[{len(vals)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n"
out = []
out.append('''// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// ggml-metal-bposit8.h — GENERATED by ggml/src/ggml-metal/gen-bposit8-header.py from
// ggml/src/ggml-det/{det_soft.h,bp8_exact_soft.h,det_soft_ops.h}. Do not edit by hand. Self-contained: the Metal
// library embedder inlines it into ggml-metal.metal.
//
// b-posit8 W8A8 exact-quire matmul for Metal. Contract: every output float is bit-identical to
// the CPU kernel (ggml-cpu/quants.c) and to the CUDA kernel (ggml-cuda/bposit8.cu). Metal has no
// double, so the reference's double arithmetic (nearest-code encode, 256-bit -> double -> float
// readout) is performed by a software IEEE binary64 on 64-bit integers, gated against hardware
// double on 2e8 cases and against libggml-cpu on 3e5 rows (space-time/research/metal-exact).
#ifndef GGML_METAL_BPOSIT8_H
#define GGML_METAL_BPOSIT8_H
''')
out.append(body('det_soft.h'))
out.append(body('bp8_exact_soft.h'))
out.append(body('det_soft_ops.h').replace('#include "det_soft.h"\n', ''))
out.append('\n#ifdef __METAL_VERSION__\n')
out.append(carr('ulong', 'bp8_tab_sv', sv, lambda v: f"0x{v:016x}ul"))
out.append(carr('uint',  'bp8_tab_sc', codes, lambda v: f"{v}"))
out.append(carr('int',   'bp8_tab_M',  tM, lambda v: f"{v}"))
out.append(carr('int',   'bp8_tab_E',  tE, lambda v: f"{v}"))
out.append(r'''
#define BP8_NSG 4   // simdgroups (output rows) per threadgroup

// one thread per 32-element block of src1 (f32) -> block_bposit8, blocks laid out [i3][i2][i1][ib]
kernel void kernel_quantize_bposit8_f32(
        constant ggml_metal_kargs_bp8_quant & args,
        device const float * x,
        device block_bposit8 * y,
        uint tid [[thread_position_in_grid]]) {
    const long b = (long) tid;
    if (b >= args.nblk_total) return;
    const long ib = b % args.nblk_row;
    long r = b / args.nblk_row;
    const long i1 = r % args.ne1; r /= args.ne1;
    const long i2 = r % args.ne2;
    const long i3 = r / args.ne2;
    device const float * xr = x + i3 * args.s3 + i2 * args.s2 + i1 * args.s1 + ib * BP8_QK;
    uint xb[BP8_QK];
    for (int j = 0; j < BP8_QK; j++) xb[j] = as_type<uint>(xr[j]);
    int se; uint qs[BP8_QK];
    bp8_quantize_block_soft(xb, &se, qs, bp8_tab_sv, bp8_tab_sc);
    device block_bposit8 * yb = y + b;
    yb->scale_exp = (char) se;
    for (int j = 0; j < BP8_QK; j++) yb->qs[j] = (uchar) qs[j];
}

// simdgroup quantise: one simdgroup per 32-element block, one lane per element. The block scale
// needs the exact sum of squares: each lane adds its square into a 20-limb accumulator, the
// limbs are summed across the simdgroup (butterfly, every lane gets the total) and
// carry-normalised, then each lane encodes its own element. Same results as the one-thread
// kernel above (bp8_ss_add_sq / bp8_ss_finish are the pieces of bp8_scale_exp_exact_bits).
// nearest-code search on threadgroup-resident tables (the constant-memory search serialises on
// divergent addresses); same code as bp8_encode_nearest_soft
static inline uint bp8_encode_nearest_tg(ulong x, threadgroup const ulong * sv, threadgroup const uint * sc) {
    if ((x & 0x7FFFFFFFFFFFFFFFul) == 0) return BP8_ZERO;
    int lo = 0, hi = 255;
    while (lo < hi) { const int mid = (lo + hi) >> 1; if (ds_lt(sv[mid], x)) lo = mid + 1; else hi = mid; }
    int best_k = -1; ulong bestd = 0x7FF0000000000000ul;
    const int start = lo > 0 ? lo - 1 : lo, end = lo < 255 ? lo : lo - 1;
    for (int k = start; k <= end; k++) {
        const ulong d = ds_fabs(ds_sub(sv[k], x));
        if (ds_lt(d, bestd) || (ds_eq(d, bestd) && (best_k < 0 || sc[k] < sc[best_k]))) { bestd = d; best_k = k; }
    }
    if (best_k < 0 || !ds_lt(bestd, ds_fabs(x))) return BP8_ZERO;
    return sc[best_k];
}
static inline ulong bp8_simd_sum_u64(ulong v, ushort tiisg) {      // 64-bit butterfly sum via two 32-bit shuffles
    for (ushort off = 16; off > 0; off >>= 1) {
        const uint lo = simd_shuffle_xor((uint) v, off);
        const uint hi = simd_shuffle_xor((uint) (v >> 32), off);
        v += ((ulong) hi << 32) | lo;
    }
    return v;
}
kernel void kernel_quantize_bposit8_f32_sg(
        constant ggml_metal_kargs_bp8_quant & args,
        device const float * x,
        device block_bposit8 * y,
        threadgroup ulong * tabs [[threadgroup(0)]],               // sv[255] then sc[256] (as uint)
        uint3  tgpig [[threadgroup_position_in_grid]],
        ushort tiisg [[thread_index_in_simdgroup]],
        ushort sgitg [[simdgroup_index_in_threadgroup]]) {
    threadgroup uint * tsc = (threadgroup uint *) (tabs + 255);
    for (int i = (int) sgitg * 32 + tiisg; i < 255; i += BP8_NSG * 32) { tabs[i] = bp8_tab_sv[i]; tsc[i] = bp8_tab_sc[i]; }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    const long b = (long) tgpig.x * BP8_NSG + sgitg;
    if (b >= args.nblk_total) return;                              // whole simdgroup leaves together
    const long ib = b % args.nblk_row;
    long r = b / args.nblk_row;
    const long i1 = r % args.ne1; r /= args.ne1;
    const long i2 = r % args.ne2;
    const long i3 = r / args.ne2;
    const uint xb = as_type<uint>(x[i3 * args.s3 + i2 * args.s2 + i1 * args.s1 + ib * BP8_QK + tiisg]);
    uint acc[BP8_SS_LIMBS];
    for (int i = 0; i < BP8_SS_LIMBS; i++) acc[i] = 0;
    const int rr = bp8_ss_add_sq(acc, xb);
    const int nonfinite = simd_any(rr < 0);
    const int any       = simd_any(rr > 0);
    int se = 0;
    if (!nonfinite && any) {
        uint tot[BP8_SS_LIMBS];
        ulong carry = 0;
        for (int i = 0; i < BP8_SS_LIMBS; i++) {                   // per-limb sums < 32 * 2^32: no overflow
            const ulong t = bp8_simd_sum_u64((ulong) acc[i], tiisg) + carry;
            tot[i] = (uint) t; carry = t >> 32;
        }
        se = bp8_ss_finish(tot);
    }
    const ulong xd = ds_ldexp(ds_from_f32bits(xb), -se);           // exact
    const uint code = bp8_encode_nearest_tg(xd, tabs, tsc);
    device block_bposit8 * yb = y + b;
    if (tiisg == 0) yb->scale_exp = (char) se;
    yb->qs[tiisg] = (uchar) code;
}

// exact dot: one simdgroup per output element; lanes stride the blocks; 8 int64 limbs per lane
// summed through threadgroup memory, carry-normalised once, read out through the software double
kernel void kernel_mul_mv_bposit8_exact(
        constant ggml_metal_kargs_bp8_mv & args,
        device const block_bposit8 * x,
        device const block_bposit8 * y,
        device float * dst,
        threadgroup short * tab [[threadgroup(0)]],     // 256 x (M << 8 | E & 0xFF): the decode table, threadgroup-resident
        threadgroup long * tgacc [[threadgroup(1)]],    // per-lane 8 limbs, interleaved [sg][w][lane] (see below)
        uint3  tgpig [[threadgroup_position_in_grid]],
        ushort tiisg [[thread_index_in_simdgroup]],
        ushort sgitg [[simdgroup_index_in_threadgroup]]) {
    const int  lane = tiisg;
    // constant-memory lookups with divergent indices serialise; copy the table to threadgroup memory
    for (int i = (int) sgitg * 32 + lane; i < 256; i += BP8_NSG * 32) tab[i] = (short) ((bp8_tab_M[i] << 8) | (bp8_tab_E[i] & 0xFF));
    threadgroup_barrier(mem_flags::mem_threadgroup);
    const long row  = (long) tgpig.x * BP8_NSG + sgitg;
    if (row >= args.ne01) return;                              // the whole simdgroup leaves together
    const long i1 = tgpig.y;
    const long i2 = tgpig.z % args.ne12, i3 = tgpig.z / args.ne12;
    device const block_bposit8 * xr = x + (i3 / args.r3) * args.s03 + (i2 / args.r2) * args.s02 + row * args.s01;
    device const block_bposit8 * yr = y + i3 * args.s13 + i2 * args.s12 + i1 * args.s11;
    // the limb index of each product is data-dependent; a dynamically indexed private array is
    // demoted to slow memory on Apple GPUs (measured 2.9x of the kernel's time), so the lazily
    // carried limbs live in threadgroup memory, limb-major so lanes hit consecutive words
    threadgroup long * a0 = tgacc + (int) sgitg * 8 * 32 + lane;
#define BP8_A(w) a0[(w) * 32]
    for (int w = 0; w < 8; w++) BP8_A(w) = 0;
    for (int ib = lane; ib < args.nblk; ib += 32) {
        const int se = (int) xr[ib].scale_exp + (int) yr[ib].scale_exp + BP8_QFRAC;
        device const uchar * qx = xr[ib].qs;
        device const uchar * qy = yr[ib].qs;
        for (int j = 0; j < BP8_QK; j++) {
            const short tx = tab[qx[j]], ty = tab[qy[j]];
            const int P = (int) (tx >> 8) * (int) (ty >> 8);
            if (P == 0) continue;
            // == bp8_lane_add(a, P, sh) on the threadgroup limbs (sh >= 48 here: w >= 1)
            const int sh = (int) (char) tx + (int) (char) ty + se;
            const int w = sh >> 5, bits = sh & 31;
            const long V = (long) P << bits;
            BP8_A(w) += (long) (uint) V;
            if (w + 1 < 8) BP8_A(w + 1) += (V >> 32);
        }
    }
    // simdgroup reduction of the 8 limbs by butterfly shuffles (two's complement wraps correctly)
    long s[8];
    for (int w = 0; w < 8; w++) s[w] = (long) bp8_simd_sum_u64((ulong) BP8_A(w), tiisg);
#undef BP8_A
    if (lane != 0) return;
    uint q[8];
    bp8_limbs_to_q256(s, q);
    const uint out = bp8_q256_to_f32bits_fast(q);
    dst[i3 * args.sd3 + i2 * args.sd2 + i1 * args.sd1 + row] = as_type<float>(out);
}

// get_rows for b-posit8 (the embedding lookup): the CPU's (float)(value[code] * 2^scale_exp) on
// the software double — the same single rounding, subnormal floats included. One thread per 16
// elements (the op's ne00t = ne00/16 convention for quantised types).
kernel void kernel_get_rows_bposit8(
        constant ggml_metal_kargs_get_rows & args,
        device const void * src0,
        device const void * src1,
        device       void * dst,
        uint3               tgpig[[threadgroup_position_in_grid]],
        ushort              tiitg[[thread_index_in_threadgroup]],
        ushort3             ntg  [[threads_per_threadgroup]]) {
    const int32_t iw0 = tgpig.x/args.ne10;
    const int32_t i10 = tgpig.x%args.ne10;
    const int32_t i11 = tgpig.y;
    const int32_t i12 = tgpig.z;
    const int32_t r = ((const device int32_t *) ((const device char *) src1 + i12*args.nb12 + i11*args.nb11 + i10*args.nb10))[0];
    const int32_t i02 = i11;
    const int32_t i03 = i12;
    device const block_bposit8 * psrc = (device const block_bposit8 *) ((const device char *) src0 + i03*args.nb03 + i02*args.nb02 + r*args.nb01);
    device       float         * pdst = (device       float *)         ((      device char *) dst  + i12*args.nb3  + i11*args.nb2  + i10*args.nb1);
    const int ind = iw0*ntg.x + tiitg;
    if (ind >= args.ne00t) return;
    device const block_bposit8 * b = psrc + ind/2;
    const int se = (int) b->scale_exp;
    const int j0 = (ind % 2) * 16;
    for (int j = 0; j < 16; j++) {
        const ulong v = bp8_code_to_dbits((uint) b->qs[j0 + j]);       // exact value of the code (double bits)
        pdst[ind * 16 + j] = as_type<float>(ds_to_f32bits(v == 0 ? 0ul : ds_ldexp(v, se)));
    }
}

// ---------------------------------------------------------------------------------------
// exact f16 matmul (attention KQ / KQV with -fa off): src1 f32 -> f16 (IEEE RN-even, integer
// form == ggml_cpu_fp32_to_fp16), then det_dot_f16 per output: products M*M at 2^(Ex+Ey) into
// the same lazily-carried 256-bit quire and the same limb-to-double readout as the CPU path
// ---------------------------------------------------------------------------------------
static inline ushort dso_f32_to_f16bits(uint w) {
    const uint sign = (w >> 16) & 0x8000u;
    const int  e    = (int) ((w >> 23) & 0xFFu);
    const uint m    = w & 0x7FFFFFu;
    if (e == 0xFF) return (ushort) (sign | 0x7C00u | (m ? (0x200u | (m >> 13)) : 0u));   // inf / quiet NaN
    const int E = e - 112;                                       // f16 biased exponent
    uint mant; int shift;
    if (E > 0) { mant = m | 0x800000u; shift = 13; }
    else       { if (e == 0) return (ushort) sign; mant = m | 0x800000u; shift = 13 + (1 - E); if (shift > 24) return (ushort) sign; }
    uint q = mant >> shift;
    const uint rem = mant & ((1u << shift) - 1u), half_ = 1u << (shift - 1);
    if (rem > half_ || (rem == half_ && (q & 1u))) q++;
    uint out = (E > 0) ? (((uint) E << 10) + q - (1u << 10)) : q;   // q carries into the exponent when it overflows
    if (out >= 0x7C00u) out = 0x7C00u;                            // overflow -> inf
    return (ushort) (sign | out);
}
// IEEE binary16 -> M * 2^E (M = 0 for inf/nan), == det_f16_to_ME
static inline void dso_f16_to_ME(uint h, thread int * M, thread int * E) {
    const int s = (h >> 15) & 1, e = (h >> 10) & 0x1F, f = h & 0x3FF;
    int m;
    if (e == 0)       { m = f;        *E = -24; }
    else if (e == 31) { m = 0;        *E = 0;   }
    else              { m = 1024 + f; *E = e - 25; }
    *M = s ? -m : m;
}
// one thread per element of src1 (f32, strided rows) -> contiguous f16 [i3][i2][i1][k]
kernel void kernel_cvt_f32_f16_det(
        constant ggml_metal_kargs_bp8_quant & args,   // nblk_row = ne10, nblk_total = elements
        device const float * x,
        device ushort * y,
        uint tid [[thread_position_in_grid]]) {
    const long t = (long) tid;
    if (t >= args.nblk_total) return;
    const long k = t % args.nblk_row;
    long r = t / args.nblk_row;
    const long i1 = r % args.ne1; r /= args.ne1;
    const long i2 = r % args.ne2;
    const long i3 = r / args.ne2;
    y[t] = dso_f32_to_f16bits(as_type<uint>(x[i3 * args.s3 + i2 * args.s2 + i1 * args.s1 + k]));
}
// one simdgroup per output element; lanes stride k; strides in elements (src0 nb00 == 2)
kernel void kernel_mul_mv_f16_exact(
        constant ggml_metal_kargs_bp8_mv & args,      // nblk = ne00
        device const ushort * x,
        device const ushort * y,
        device float * dst,
        threadgroup long * tgacc [[threadgroup(0)]],    // per-lane 8 limbs, interleaved [sg][w][lane]
        uint3  tgpig [[threadgroup_position_in_grid]],
        ushort tiisg [[thread_index_in_simdgroup]],
        ushort sgitg [[simdgroup_index_in_threadgroup]]) {
    const int  lane = tiisg;
    const long row  = (long) tgpig.x * BP8_NSG + sgitg;
    if (row >= args.ne01) return;
    const long i1 = tgpig.y;
    const long i2 = tgpig.z % args.ne12, i3 = tgpig.z / args.ne12;
    device const ushort * xr = x + (i3 / args.r3) * args.s03 + (i2 / args.r2) * args.s02 + row * args.s01;
    device const ushort * yr = y + i3 * args.s13 + i2 * args.s12 + i1 * args.s11;
    threadgroup long * a0 = tgacc + (int) sgitg * 8 * 32 + lane;
#define BP8_A(w) a0[(w) * 32]
    for (int w = 0; w < 8; w++) BP8_A(w) = 0;
    for (int k = lane; k < args.nblk; k += 32) {
        int Mx, Ex, My, Ey;
        dso_f16_to_ME(xr[k], &Mx, &Ex);
        dso_f16_to_ME(yr[k], &My, &Ey);
        const int P = Mx * My;
        if (P == 0) continue;
        const int sh = Ex + Ey + BP8_QFRAC;                    // in [48, 106]: w in [1, 3]
        const int w = sh >> 5, bits = sh & 31;
        const long V = (long) P << bits;
        BP8_A(w) += (long) (uint) V;
        BP8_A(w + 1) += (V >> 32);
    }
    long s[8];
    for (int w = 0; w < 8; w++) s[w] = (long) bp8_simd_sum_u64((ulong) BP8_A(w), tiisg);
#undef BP8_A
    if (lane != 0) return;
    uint q[8];
    bp8_limbs_to_q256(s, q);
    const uint out = bp8_q256_to_f32bits_fast(q);
    dst[i3 * args.sd3 + i2 * args.sd2 + i1 * args.sd1 + row] = as_type<float>(out);
}

// ---------------------------------------------------------------------------------------
// exact-profile elementwise / row ops on the software double (contract off is set by the
// #pragma in ggml-metal.metal under ANOMLY_METAL_EXACT)
// ---------------------------------------------------------------------------------------
#define DSO_NLIMB 20

// 64-bit simdgroup sum of one value via two 32-bit shuffles
static inline ulong dso_simd_sum_u64(ulong v, ushort tiisg) {
    for (ushort off = 16; off > 0; off >>= 1) {
        const uint lo = simd_shuffle_xor((uint) v, off);
        const uint hi = simd_shuffle_xor((uint) (v >> 32), off);
        v += ((ulong) hi << 32) | lo;
    }
    return v;
}
// reduce a per-thread 20-limb accumulator over the threadgroup into `out` (thread 0 only,
// carry-normalised 32-bit limbs). red: threadgroup ulong[nsg*20]. All threads must call.
static inline void dso_big_reduce_tg(thread const uint * acc, threadgroup ulong * red, thread uint * out,
                                     ushort tiisg, ushort sgitg, ushort nsg, ushort tpitg) {
    for (int i = 0; i < DSO_NLIMB; i++) {
        const ulong v = dso_simd_sum_u64((ulong) acc[i], tiisg);
        if (tiisg == 0) red[sgitg * DSO_NLIMB + i] = v;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (tpitg == 0) {
        ulong carry = 0;
        for (int i = 0; i < DSO_NLIMB; i++) {
            ulong t = carry;
            for (ushort g = 0; g < nsg; g++) t += red[g * DSO_NLIMB + i];   // < nsg * 2^37 + carry: no overflow
            out[i] = (uint) t; carry = t >> 32;
        }
    }
}

// same, but the reduced limbs are broadcast: EVERY thread leaves with `out` filled and the
// tail of the kernel stays uniform (a heavy thread-0-only block followed by a barrier and a
// threadgroup broadcast miscompiled on the M4 Pro: the other threads never ran the tail)
static inline void dso_big_reduce_tg_bcast(thread const uint * acc, threadgroup ulong * red, thread uint * out,
                                           ushort tiisg, ushort sgitg, ushort nsg, ushort tpitg) {
    dso_big_reduce_tg(acc, red, out, tiisg, sgitg, nsg, tpitg);
    if (tpitg == 0) { for (int i = 0; i < DSO_NLIMB; i++) red[i] = out[i]; }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (int i = 0; i < DSO_NLIMB; i++) out[i] = (uint) red[i];
}

// RMSNorm: F == 1 plain, F == 2 fused mul, F == 3 fused mul + add — the reference's rounding order
template <short F>
kernel void kernel_rms_norm_exact_impl(
        constant ggml_metal_kargs_norm & args,
        device const char * src0,
        device const char * src1_0,
        device const char * src1_1,
        device       char * dst,
        threadgroup ulong * red [[threadgroup(0)]],
        uint3   tgpig[[threadgroup_position_in_grid]],
        ushort3 tpitg[[thread_position_in_threadgroup]],
        ushort  sgitg[[simdgroup_index_in_threadgroup]],
        ushort  tiisg[[thread_index_in_simdgroup]],
        ushort3   ntg[[threads_per_threadgroup]]) {
    const int i01 = tgpig.x, i02 = tgpig.y, i03 = tgpig.z;
    device const float * x  = (device const float *) (src0 + i03*args.nbf3[0] + i02*args.nbf2[0] + i01*args.nbf1[0]);
    device const float * f0 = (device const float *) (src1_0 + (i03%args.nef3[1])*args.nbf3[1] + (i02%args.nef2[1])*args.nbf2[1] + (i01%args.nef1[1])*args.nbf1[1]);
    device const float * f1 = (device const float *) (src1_1 + (i03%args.nef3[2])*args.nbf3[2] + (i02%args.nef2[2])*args.nbf2[2] + (i01%args.nef1[2])*args.nbf1[2]);
    const ushort nsg = (ntg.x + 31) / 32;           // the op rounds nth up to whole simdgroups
    uint acc[DSO_NLIMB]; dso_big_zero(acc);
    int finite = 1;
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += ntg.x) finite &= dso_big_add_sq_bits(acc, as_type<uint>(x[i00]));
    finite = simd_min(finite);
    threadgroup float * bc = (threadgroup float *) (red + 32 * DSO_NLIMB);   // [0] scale, [2 + sg] finite flags
    if (tiisg == 0) bc[2 + sgitg] = (float) finite;
    uint S[DSO_NLIMB];
    dso_big_reduce_tg(acc, red, S, tiisg, sgitg, nsg, tpitg.x);            // contains the barrier
    if (tpitg.x == 0) {
        int all_finite = 1;
        for (ushort g = 0; g < nsg; g++) all_finite &= (bc[2 + g] != 0.0f);
        const ulong sumsq = all_finite ? dso_big_to_double(S) : DSO_INF;
        bc[0] = dso_rms_scale(sumsq, args.ne00, args.eps);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    const float scale = bc[0];
    device float * y = (device float *) (dst + i03*args.nb3 + i02*args.nb2 + i01*args.nb1);
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += ntg.x) {
        if (F == 1) y[i00] = DSO_FMUL(x[i00], scale);
        if (F == 2) y[i00] = DSO_FMUL(DSO_FMUL(x[i00], scale), f0[i00]);
        if (F == 3) y[i00] = DSO_FADD(DSO_FMUL(DSO_FMUL(x[i00], scale), f0[i00]), f1[i00]);
    }
}
typedef decltype(kernel_rms_norm_exact_impl<1>) kernel_rms_norm_exact_t;
template [[host_name("kernel_rms_norm_f32_exact")]]         kernel kernel_rms_norm_exact_t kernel_rms_norm_exact_impl<1>;
template [[host_name("kernel_rms_norm_mul_f32_exact")]]     kernel kernel_rms_norm_exact_t kernel_rms_norm_exact_impl<2>;
template [[host_name("kernel_rms_norm_mul_add_f32_exact")]] kernel kernel_rms_norm_exact_t kernel_rms_norm_exact_impl<3>;

// mask element -> float bits (f16 masks converted in integers: no FTZ on subnormal halves)
static inline uint dso_mask_f32bits(half m)  { return dso_f16_to_f32bits((uint) as_type<ushort>(m)); }
static inline uint dso_mask_f32bits(float m) { return as_type<uint>(m); }

// softmax (no ALiBi: max_bias == 0 is enforced by supports_op): wp = x*scale + slope*mask,
// max, y = expf(wp - max), EXACT sum (+ sink), y *= 1/(float)sum
template<typename TM>
kernel void kernel_soft_max_exact(
        constant ggml_metal_kargs_soft_max & args,
        device const  char * src0,
        device const  char * src1,
        device const  char * src2,
        device        char * dst,
        threadgroup  ulong * red [[threadgroup(0)]],
        uint3 tgpig[[threadgroup_position_in_grid]],
        uint3 tpitg[[thread_position_in_threadgroup]],
        uint  sgitg[[simdgroup_index_in_threadgroup]],
        uint  tiisg[[thread_index_in_simdgroup]],
        uint3  tptg[[threads_per_threadgroup]]) {
    const int32_t i03 = tgpig.z, i02 = tgpig.y, i01 = tgpig.x;
    const int32_t i13 = i03%args.ne13, i12 = i02%args.ne12, i11 = i01;
    device const float * psrc0 =                (device const float *) (src0 + i01*args.nb01 + i02*args.nb02 + i03*args.nb03);
    device const    TM * pmask = src1 != src0 ? (device const TM *   ) (src1 + i11*args.nb11 + i12*args.nb12 + i13*args.nb13) : nullptr;
    device const float * psrc2 = src2 != src0 ? (device const float *) (src2)                                                 : nullptr;
    device       float * pdst  =                (device       float *) (dst  + i01*args.nb1  + i02*args.nb2  + i03*args.nb3);
    threadgroup uint * fb = (threadgroup uint *) (red + 32 * DSO_NLIMB);   // [0..31] per-simdgroup max (float bits)
    const ushort nsg = (tptg.x + 31) / 32;
    const uint scale_b = as_type<uint>(args.scale);
    // all float ops on the software binary32 (no FTZ), MAX on the bit order; slope == 1: slope*mask == mask
    // pass 1: max of wp (the reference: wp = x*scale, then wp += slope*mask)
    uint lmax = 0xFF800000u;   // -inf
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += tptg.x) {
        uint wp = dso_fmul_bits(as_type<uint>(psrc0[i00]), scale_b);
        if (pmask) wp = dso_fadd_bits(wp, dso_mask_f32bits(pmask[i00]));
        lmax = dso_fmax_bits(lmax, wp);
    }
    uint max_b = dso_funkey(simd_max(dso_fkey(lmax)));
    if (tiisg == 0) fb[sgitg] = max_b;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    max_b = 0xFF800000u;
    for (ushort g = 0; g < nsg; g++) max_b = dso_fmax_bits(max_b, fb[g]);
    if (psrc2) max_b = dso_fmax_bits(max_b, as_type<uint>(psrc2[i02]));
    // pass 2: y = expf(wp - max), exact sum
    uint acc[DSO_NLIMB]; dso_big_zero(acc);
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += tptg.x) {
        uint wp = dso_fmul_bits(as_type<uint>(psrc0[i00]), scale_b);
        if (pmask) wp = dso_fadd_bits(wp, dso_mask_f32bits(pmask[i00]));
        const uint yb = dso_expf_bits(dso_fsub_bits(wp, max_b));
        pdst[i00] = as_type<float>(yb);
        dso_big_add_f32_nonneg_bits(acc, yb);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);   // fb reads done before red is reused
    uint S[DSO_NLIMB];
    dso_big_reduce_tg_bcast(acc, red, S, tiisg, sgitg, nsg, tpitg.x);
    // uniform tail: every thread derives the same inv from the same limbs (psrc2 is uniform)
    if (psrc2) { const uint se = dso_expf_bits(dso_fsub_bits(as_type<uint>(psrc2[i02]), max_b)); if (!dso_f_is_zero(se)) dso_big_add_f32_nonneg_bits(S, se); }
    const uint inv_b = as_type<uint>(dso_soft_max_inv(dso_big_to_double(S)));
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += tptg.x) pdst[i00] = as_type<float>(dso_fmul_bits(as_type<uint>(pdst[i00]), inv_b));
}
typedef decltype(kernel_soft_max_exact<float>) kernel_soft_max_exact_t;
template [[host_name("kernel_soft_max_f32_exact")]] kernel kernel_soft_max_exact_t kernel_soft_max_exact<float>;
template [[host_name("kernel_soft_max_f16_exact")]] kernel kernel_soft_max_exact_t kernel_soft_max_exact<half>;

// RoPE (ext_factor == 0, f32, forward): cos/sin from the exact table rule, mscale = attn_factor
static inline void dso_rope_pair(constant ggml_metal_kargs_rope & args, device const char * src2, float theta_base, int ic,
                                 thread float * cos_theta, thread float * sin_theta) {
    uint s, c;
    if (args.src2) dso_rope_sincos_ff(as_type<uint>(theta_base), ic, args.n_dims, as_type<uint>(args.freq_base), as_type<uint>(args.freq_scale), as_type<uint>(((device const float *) src2)[ic]), &s, &c);
    else           dso_rope_sincos(as_type<uint>(theta_base), ic, args.n_dims, as_type<uint>(args.freq_base), as_type<uint>(args.freq_scale), &s, &c);
    *cos_theta = DSO_FMUL(as_type<float>(c), args.attn_factor);
    *sin_theta = DSO_FMUL(as_type<float>(s), args.attn_factor);
}
kernel void kernel_rope_norm_f32_exact(
        constant ggml_metal_kargs_rope & args,
        device const char * src0, device const char * src1, device const char * src2, device char * dst,
        ushort tiitg[[thread_index_in_threadgroup]], ushort3 tptg [[threads_per_threadgroup]], uint3 tgpig[[threadgroup_position_in_grid]]) {
    const int i3 = tgpig[2], i2 = tgpig[1], i1 = tgpig[0];
    device const int32_t * pos = (device const int32_t *) src1;
    const float theta_base = (float) pos[i2];
    for (int i0 = 2*tiitg; i0 < args.ne0; i0 += 2*tptg.x) {
        device const float * const src = (device float *)(src0 + i3*args.nb03 + i2*args.nb02 + i1*args.nb01 + i0*args.nb00);
        device       float * dst_data  = (device float *)( dst + i3*args.nb3  + i2*args.nb2  + i1*args.nb1  + i0*args.nb0);
        if (i0 < args.n_dims) {
            float c, s; dso_rope_pair(args, src2, theta_base, i0/2, &c, &s);
            const float x0 = src[0], x1 = src[1];
            dst_data[0] = DSO_FSUB(DSO_FMUL(x0, c), DSO_FMUL(x1, s));
            dst_data[1] = DSO_FADD(DSO_FMUL(x0, s), DSO_FMUL(x1, c));
        } else { dst_data[0] = src[0]; dst_data[1] = src[1]; }
    }
}
kernel void kernel_rope_neox_f32_exact(
        constant ggml_metal_kargs_rope & args,
        device const char * src0, device const char * src1, device const char * src2, device char * dst,
        ushort tiitg[[thread_index_in_threadgroup]], ushort3 tptg [[threads_per_threadgroup]], uint3 tgpig[[threadgroup_position_in_grid]]) {
    const int i3 = tgpig[2], i2 = tgpig[1], i1 = tgpig[0];
    device const int32_t * pos = (device const int32_t *) src1;
    const float theta_base = (float) pos[i2];
    for (int i0 = 2*tiitg; i0 < args.ne0; i0 += 2*tptg.x) {
        if (i0 < args.n_dims) {
            const int ic = i0/2;
            float c, s; dso_rope_pair(args, src2, theta_base, ic, &c, &s);
            device const float * const src = (device float *)(src0 + i3*args.nb03 + i2*args.nb02 + i1*args.nb01 + ic*args.nb00);
            device       float * dst_data  = (device float *)( dst + i3*args.nb3  + i2*args.nb2  + i1*args.nb1  + ic*args.nb0);
            const float x0 = src[0], x1 = src[args.n_dims/2];
            dst_data[0]             = DSO_FSUB(DSO_FMUL(x0, c), DSO_FMUL(x1, s));
            dst_data[args.n_dims/2] = DSO_FADD(DSO_FMUL(x0, s), DSO_FMUL(x1, c));
        } else {
            device const float * const src = (device float *)(src0 + i3*args.nb03 + i2*args.nb02 + i1*args.nb01 + i0*args.nb00);
            device       float * dst_data  = (device float *)( dst + i3*args.nb3  + i2*args.nb2  + i1*args.nb1  + i0*args.nb0);
            dst_data[0] = src[0]; dst_data[1] = src[1];
        }
    }
}

// SwiGLU: silu(x0) * x1 with the reference's silu
kernel void kernel_swiglu_f32_exact(
        constant ggml_metal_kargs_glu & args,
        device const char * src0, device const char * src1, device char * dst,
        uint tgpig[[threadgroup_position_in_grid]], uint tpitg[[thread_position_in_threadgroup]], uint ntg[[threads_per_threadgroup]]) {
    device const float * src0_row = (device const float *) ((device const char *) src0 + tgpig*args.nb01) + args.i00;
    device const float * src1_row = (device const float *) ((device const char *) src1 + tgpig*args.nb11) + args.i10;
    device       float * dst_row  = (device       float *) ((device       char *) dst  + tgpig*args.nb1);
    for (int i0 = tpitg; i0 < args.ne0; i0 += ntg) dst_row[i0] = DSO_FMUL(dso_siluf(src0_row[i0]), src1_row[i0]);
}

// vector overloads for the unary kernel's float4 instantiation
static inline float  dso_silu_v(float  x) { return dso_siluf(x); }
static inline float4 dso_silu_v(float4 x) { return float4(dso_siluf(x.x), dso_siluf(x.y), dso_siluf(x.z), dso_siluf(x.w)); }
static inline float  dso_scale_v(float  x, float s) { return dso_fmul(x, s); }
static inline float4 dso_scale_v(float4 x, float s) { return float4(dso_fmul(x.x, s), dso_fmul(x.y, s), dso_fmul(x.z, s), dso_fmul(x.w, s)); }
static inline float  dso_gelu_v(float  x) { return dso_geluf(x); }
static inline float4 dso_gelu_v(float4 x) { return float4(dso_geluf(x.x), dso_geluf(x.y), dso_geluf(x.z), dso_geluf(x.w)); }
#endif // __METAL_VERSION__
#endif // GGML_METAL_BPOSIT8_H
''')
dst = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), 'ggml-metal-bposit8.h')
open(dst, 'w').write(''.join(out))
print('wrote', dst, 'sv[0..2]=', [hex(v) for v in sv[:3]], 'codes', codes[:3])
