#!/usr/bin/env python3
# Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
"""Generate ggml-metal-bposit8.h: det_soft.h + bp8_exact_soft.h (portable C == MSL) + the
constant code tables + the two Metal kernels. Self-contained (no #include) so the Metal
library embedder can inline it with one sed step, like ggml-common.h."""
import os, struct, sys
HERE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'ggml-det')   # det_soft.h, bp8_exact_soft.h
def body(fn):
    s = open(os.path.join(HERE, fn)).read()
    return s.replace('#include "det_soft.h"\n', '')
BP8_ES, ZERO, NAR = 2, 0x00, 0x80
def code_to_ME(p):
    if p in (ZERO, NAR): return 0, 0
    s = (p >> 7) & 1; rest = p & 0x7F
    if s: rest = ((~rest) + 1) & 0x7F
    leading = (rest >> 6) & 1; rs = 0
    while rs < 7 and ((rest >> (6 - rs)) & 1) == leading: rs += 1
    e = fb = fw = 0
    if rs == 7: k = 6 if leading else -7
    else:
        k = (rs - 1) if leading else -rs
        rem = 7 - (rs + 1); r2 = rest & ((1 << rem) - 1); ew = min(BP8_ES, rem)
        if ew > 0: e = ((r2 >> (rem - ew)) & ((1 << ew) - 1)) << (BP8_ES - ew)
        rem -= ew; fw = rem; fb = r2 & ((1 << fw) - 1) if fw > 0 else 0
    m = (1 << fw) + fb
    return (-m if s else m), 4 * k + e - fw
def dbits(M, E):
    v = M * 2.0 ** E  # exact: small M, moderate E
    return struct.unpack('<Q', struct.pack('<d', v))[0]
tM, tE = zip(*[code_to_ME(c) for c in range(256)])
codes = sorted((c for c in range(256) if c != NAR), key=lambda c: tM[c] * 2.0 ** tE[c])
sv = [dbits(tM[c], tE[c]) for c in codes]
assert len(set(sv)) == 255
def carr(t, name, vals, fmt):
    rows = [', '.join(fmt(v) for v in vals[i:i+8]) for i in range(0, len(vals), 8)]
    return f"constant {t} {name}[{len(vals)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n"
out = []
out.append('''// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// ggml-metal-bposit8.h — GENERATED by ggml/src/ggml-metal/gen-bposit8-header.py from
// ggml/src/ggml-det/{det_soft.h,bp8_exact_soft.h}. Do not edit by hand. Self-contained: the Metal
// library embedder inlines it into ggml-metal.metal.
//
// b-posit8 W8A8 exact-quire matmul for Metal. Contract: every output float is bit-identical to
// the CPU kernel (ggml-cpu/quants.c) and to the CUDA kernel (ggml-cuda/bposit8.cu). Metal has no
// double, so the reference's double arithmetic (nearest-code encode, 256-bit -> double -> float
// readout) is performed by a software IEEE binary64 on 64-bit integers, gated against hardware
// double on 2e8 cases and against libggml-cpu on 3e5 rows (space-time/research/metal-exact).
#ifndef GGML_METAL_BPOSIT8_H
#define GGML_METAL_BPOSIT8_H
''')
out.append(body('det_soft.h'))
out.append(body('bp8_exact_soft.h'))
out.append('\n#ifdef __METAL_VERSION__\n')
out.append(carr('ulong', 'bp8_tab_sv', sv, lambda v: f"0x{v:016x}ul"))
out.append(carr('uint',  'bp8_tab_sc', codes, lambda v: f"{v}"))
out.append(carr('int',   'bp8_tab_M',  tM, lambda v: f"{v}"))
out.append(carr('int',   'bp8_tab_E',  tE, lambda v: f"{v}"))
out.append(r'''
#define BP8_NSG 4   // simdgroups (output rows) per threadgroup

// one thread per 32-element block of src1 (f32) -> block_bposit8, blocks laid out [i3][i2][i1][ib]
kernel void kernel_quantize_bposit8_f32(
        constant ggml_metal_kargs_bp8_quant & args,
        device const float * x,
        device block_bposit8 * y,
        uint tid [[thread_position_in_grid]]) {
    const long b = (long) tid;
    if (b >= args.nblk_total) return;
    const long ib = b % args.nblk_row;
    long r = b / args.nblk_row;
    const long i1 = r % args.ne1; r /= args.ne1;
    const long i2 = r % args.ne2;
    const long i3 = r / args.ne2;
    device const float * xr = x + i3 * args.s3 + i2 * args.s2 + i1 * args.s1 + ib * BP8_QK;
    uint xb[BP8_QK];
    for (int j = 0; j < BP8_QK; j++) xb[j] = as_type<uint>(xr[j]);
    int se; uint qs[BP8_QK];
    bp8_quantize_block_soft(xb, &se, qs, bp8_tab_sv, bp8_tab_sc);
    device block_bposit8 * yb = y + b;
    yb->scale_exp = (char) se;
    for (int j = 0; j < BP8_QK; j++) yb->qs[j] = (uchar) qs[j];
}

// exact dot: one simdgroup per output element; lanes stride the blocks; 8 int64 limbs per lane
// summed through threadgroup memory, carry-normalised once, read out through the software double
kernel void kernel_mul_mv_bposit8_exact(
        constant ggml_metal_kargs_bp8_mv & args,
        device const block_bposit8 * x,
        device const block_bposit8 * y,
        device float * dst,
        threadgroup long * red [[threadgroup(0)]],
        uint3  tgpig [[threadgroup_position_in_grid]],
        ushort tiisg [[thread_index_in_simdgroup]],
        ushort sgitg [[simdgroup_index_in_threadgroup]]) {
    const int  lane = tiisg;
    const long row  = (long) tgpig.x * BP8_NSG + sgitg;
    if (row >= args.ne01) return;                              // the whole simdgroup leaves together
    const long i1 = tgpig.y;
    const long i2 = tgpig.z % args.ne12, i3 = tgpig.z / args.ne12;
    device const block_bposit8 * xr = x + (i3 / args.r3) * args.s03 + (i2 / args.r2) * args.s02 + row * args.s01;
    device const block_bposit8 * yr = y + i3 * args.s13 + i2 * args.s12 + i1 * args.s11;
    long a[8];
    for (int w = 0; w < 8; w++) a[w] = 0;
    for (int ib = lane; ib < args.nblk; ib += 32) {
        const int se = (int) xr[ib].scale_exp + (int) yr[ib].scale_exp + BP8_QFRAC;
        for (int j = 0; j < BP8_QK; j++) {
            const uint cx = xr[ib].qs[j], cy = yr[ib].qs[j];
            const int P = bp8_tab_M[cx] * bp8_tab_M[cy];
            if (P == 0) continue;
            bp8_lane_add(a, (long) P, bp8_tab_E[cx] + bp8_tab_E[cy] + se);
        }
    }
    threadgroup long * r = red + ((int) sgitg * 32) * 8;
    for (int w = 0; w < 8; w++) r[lane * 8 + w] = a[w];
    metal::simdgroup_barrier(metal::mem_flags::mem_threadgroup);
    if (lane != 0) return;
    long s[8];
    for (int w = 0; w < 8; w++) { long t = 0; for (int l = 0; l < 32; l++) t += r[l * 8 + w]; s[w] = t; }
    uint q[8];
    bp8_limbs_to_q256(s, q);
    const uint out = bp8_q256_to_f32bits(q);
    dst[i3 * args.sd3 + i2 * args.sd2 + i1 * args.sd1 + row] = as_type<float>(out);
}
#endif // __METAL_VERSION__
#endif // GGML_METAL_BPOSIT8_H
''')
dst = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), 'ggml-metal-bposit8.h')
open(dst, 'w').write(''.join(out))
print('wrote', dst, 'sv[0..2]=', [hex(v) for v in sv[:3]], 'codes', codes[:3])
