// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// ggml-metal-bposit8.h — GENERATED by ggml/src/ggml-metal/gen-bposit8-header.py from
// ggml/src/ggml-det/{det_soft.h,bp8_exact_soft.h}. Do not edit by hand. Self-contained: the Metal
// library embedder inlines it into ggml-metal.metal.
//
// b-posit8 W8A8 exact-quire matmul for Metal. Contract: every output float is bit-identical to
// the CPU kernel (ggml-cpu/quants.c) and to the CUDA kernel (ggml-cuda/bposit8.cu). Metal has no
// double, so the reference's double arithmetic (nearest-code encode, 256-bit -> double -> float
// readout) is performed by a software IEEE binary64 on 64-bit integers, gated against hardware
// double on 2e8 cases and against libggml-cpu on 3e5 rows (space-time/research/metal-exact).
#ifndef GGML_METAL_BPOSIT8_H
#define GGML_METAL_BPOSIT8_H
// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// det_soft.h — software IEEE-754 binary64 add/sub (round-to-nearest-even) and binary64 ->
// binary32 conversion on 64-bit integers, for targets without double (Metal). Written so the
// same text compiles as C and as Metal Shading Language: only fixed-width integers, no libm.
// Gate: research/metal-exact/test_det_soft.c compares every routine against hardware double.
#ifndef DET_SOFT_H
#define DET_SOFT_H

#ifdef __METAL_VERSION__
#define DS_FN static inline
#define DS_PTR(T) thread T *
#define DS_CLZ64(x) ((int)metal::clz((metal::ulong)(x)))
typedef ulong ds_u64; typedef long ds_i64; typedef uint ds_u32; typedef int ds_i32;   // after `using namespace metal;`
#else
#include <stdint.h>
#define DS_FN static inline
#define DS_PTR(T) T *
#define DS_CLZ64(x) __builtin_clzll((unsigned long long)(x))
typedef uint64_t ds_u64; typedef int64_t ds_i64; typedef uint32_t ds_u32; typedef int32_t ds_i32;
#endif

// ---- binary64 layout helpers (bits form) ----
DS_FN ds_u64 ds_sign(ds_u64 a) { return a >> 63; }
DS_FN ds_i32 ds_exp(ds_u64 a)  { return (ds_i32)((a >> 52) & 0x7FF); }
DS_FN ds_u64 ds_frac(ds_u64 a) { return a & 0xFFFFFFFFFFFFFull; }
DS_FN ds_u64 ds_pack(ds_u64 s, ds_i32 e, ds_u64 f) { return (s << 63) | ((ds_u64)e << 52) | f; }

// value = m * 2^(e - 52) with m the full significand (hidden bit set for normals); zero -> m=0
DS_FN void ds_unpack(ds_u64 a, DS_PTR(ds_u64) m, DS_PTR(ds_i32) e) {
    ds_i32 ex = ds_exp(a); ds_u64 f = ds_frac(a);
    if (ex == 0) { *m = f; *e = 1; }                 // subnormal or zero: exponent 1, no hidden bit
    else         { *m = f | (1ull << 52); *e = ex; }
}

// round a positive value given as (mant, e) where value = mant * 2^(e-52-EXTRA) with EXTRA
// guard bits below the 53-bit target, sticky already folded into bit 0 of mant.
// Returns packed bits (sign applied by caller). mant may exceed 53+EXTRA bits by one (carry).
#define DS_EXTRA 10
DS_FN ds_u64 ds_round_pack(ds_u64 s, ds_i64 e, ds_u64 mant) {
    if (mant == 0) return s << 63;
    // normalise so the leading bit is at position 52 + DS_EXTRA
    ds_i32 lz = DS_CLZ64(mant);
    ds_i32 want = 63 - (52 + DS_EXTRA);              // leading zeros wanted
    if (lz > want) { mant <<= (lz - want); e -= (lz - want); }
    else if (lz < want) {                            // shift right with sticky
        ds_i32 sh = want - lz;
        ds_u64 lost = mant & ((1ull << sh) - 1);
        mant = (mant >> sh) | (lost ? 1ull : 0ull);
        e += sh;
    }
    // subnormal handling: if e < 1, shift right further (with sticky) so exponent field is 0
    if (e < 1) {
        ds_i64 sh = 1 - e;
        if (sh > 63) { mant = (mant ? 1ull : 0ull); }
        else { ds_u64 lost = mant & ((1ull << sh) - 1); mant = (mant >> sh) | (lost ? 1ull : 0ull); }
        e = 1;
    }
    // round to nearest even on the DS_EXTRA guard bits
    ds_u64 guard = mant & ((1ull << DS_EXTRA) - 1);
    ds_u64 hmid  = 1ull << (DS_EXTRA - 1);
    ds_u64 q = mant >> DS_EXTRA;
    if (guard > hmid || (guard == hmid && (q & 1ull))) q += 1;
    if (q >> 53) { q >>= 1; e += 1; }                 // rounding carry
    if (e >= 0x7FF) return ds_pack(s, 0x7FF, 0);      // overflow -> inf
    if ((q >> 52) == 0) return ds_pack(s, 0, q);      // stayed subnormal (or zero)
    return ds_pack(s, (ds_i32)e, q & 0xFFFFFFFFFFFFFull);
}

// a + b, both finite, IEEE RNE. (No NaN/inf inputs in our uses; zeros handled.)
DS_FN ds_u64 ds_add(ds_u64 a, ds_u64 b) {
    ds_u64 ma, mb; ds_i32 ea, eb;
    ds_unpack(a, &ma, &ea); ds_unpack(b, &mb, &eb);
    ds_u64 sa = ds_sign(a), sb = ds_sign(b);
    if (ma == 0 && mb == 0) return (sa & sb) << 63;   // -0 + -0 = -0, else +0
    if (ma == 0) return b;
    if (mb == 0) return a;
    // make a the larger magnitude (by exponent then mantissa)
    if (ea < eb || (ea == eb && ma < mb)) { ds_u64 t = ma; ma = mb; mb = t; ds_i32 te = ea; ea = eb; eb = te; ds_u64 ts = sa; sa = sb; sb = ts; }
    ma <<= DS_EXTRA; mb <<= DS_EXTRA;                 // 63-bit working width
    ds_i32 d = ea - eb;
    if (d > 0) {
        if (d >= 64) mb = (mb ? 1ull : 0ull);
        else { ds_u64 lost = mb & ((1ull << d) - 1); mb = (mb >> d) | (lost ? 1ull : 0ull); }
    }
    ds_u64 mant;
    if (sa == sb) mant = ma + mb; else mant = ma - mb; // ma >= mb by construction
    if (mant == 0) return 0;                          // exact cancellation -> +0 (RNE)
    return ds_round_pack(sa, ea, mant);
}
DS_FN ds_u64 ds_neg(ds_u64 a) { return a ^ (1ull << 63); }
DS_FN ds_u64 ds_sub(ds_u64 a, ds_u64 b) { return ds_add(a, ds_neg(b)); }
DS_FN ds_u64 ds_fabs(ds_u64 a) { return a & 0x7FFFFFFFFFFFFFFFull; }
// ordering of finite doubles (no NaN): a < b
DS_FN ds_i64 ds_key(ds_u64 a) { return (a >> 63) ? -(ds_i64)(a & 0x7FFFFFFFFFFFFFFFull) : (ds_i64)a; }
DS_FN int ds_lt(ds_u64 a, ds_u64 b) { return ds_key(a) < ds_key(b); }
DS_FN int ds_eq(ds_u64 a, ds_u64 b) { return ds_key(a) == ds_key(b); }
// exact scaling by 2^k (no overflow in our uses; underflow to subnormal handled by repack)
DS_FN ds_u64 ds_ldexp(ds_u64 a, ds_i32 k) {
    ds_u64 m; ds_i32 e; ds_unpack(a, &m, &e);
    if (m == 0) return a;
    return ds_round_pack(ds_sign(a), (ds_i64)e + k, m << DS_EXTRA);
}
// exact conversions
DS_FN ds_u64 ds_from_u32(ds_u32 v) { return v ? ds_round_pack(0, 1075, ((ds_u64)v) << DS_EXTRA) : 0; }   // e biased: value = m*2^(e-1075)
DS_FN ds_u64 ds_from_i64_exact(ds_i64 v) {        // |v| < 2^53 assumed exact
    ds_u64 s = v < 0; ds_u64 m = s ? (ds_u64)(-v) : (ds_u64)v;
    return m ? ds_round_pack(s, 1075, m << DS_EXTRA) : 0;
}
// float32 bits -> exact binary64 bits (finite inputs)
DS_FN ds_u64 ds_from_f32bits(ds_u32 f) {
    ds_u64 s = f >> 31; ds_i32 e = (f >> 23) & 0xFF; ds_u64 m = f & 0x7FFFFF;
    if (e == 0) { if (m == 0) return s << 63; return ds_round_pack(s, 1 - 127 + 1023 - 23 + 52, m << DS_EXTRA); }
    return ds_round_pack(s, (ds_i64)e - 127 + 1023, (m | 0x800000ull) << (29 + DS_EXTRA));
}
// binary64 -> binary32 bits, RNE, with subnormal floats and overflow to inf
DS_FN ds_u32 ds_to_f32bits(ds_u64 a) {
    ds_u64 s = ds_sign(a); ds_u64 m; ds_i32 e; ds_unpack(a, &m, &e);
    if (m == 0) return (ds_u32)(s << 31);
    ds_i32 lz = DS_CLZ64(m);                          // normalise leading bit to 52 for subnormal doubles
    if (lz > 11) { m <<= (lz - 11); e -= (lz - 11); }
    ds_i64 fe = (ds_i64)e - 1023 + 127;               // float exponent field candidate
    // keep 24 bits + guard: shift m (53 bits) right by 29 with sticky -> q has 24 bits + we need RNE
    ds_i32 sh = 29;
    if (fe < 1) { sh += (ds_i32)(1 - fe); fe = 1; }   // float subnormal: denormalise
    ds_u64 q, lost, hmid;
    if (sh > 64) return (ds_u32)(s << 31);                       // below hmid the smallest subnormal
    if (sh == 64) { q = 0; lost = m; hmid = 1ull << 63; }
    else { q = m >> sh; lost = m & ((1ull << sh) - 1); hmid = 1ull << (sh - 1); }
    if (lost > hmid || (lost == hmid && (q & 1ull))) q += 1;
    if (q >> 24) { q >>= 1; fe += 1; }
    if (fe >= 0xFF) return (ds_u32)((s << 31) | 0x7F800000u);
    if ((q >> 23) == 0) return (ds_u32)((s << 31) | (ds_u32)q);   // subnormal float (or zero)
    return (ds_u32)((s << 31) | ((ds_u32)fe << 23) | ((ds_u32)q & 0x7FFFFFu));
}

// ---- multiply, divide, floor, integer conversions (for the norm / softmax / rope ports) ----
#ifdef __METAL_VERSION__
#define DS_MULHI64(a, b) ((ds_u64)metal::mulhi((ulong)(a), (ulong)(b)))
#else
#define DS_MULHI64(a, b) ((ds_u64)(((unsigned __int128)(a) * (unsigned __int128)(b)) >> 64))
#endif
// a * b, finite inputs, IEEE RNE
DS_FN ds_u64 ds_mul(ds_u64 a, ds_u64 b) {
    ds_u64 ma, mb; ds_i32 ea, eb;
    ds_unpack(a, &ma, &ea); ds_unpack(b, &mb, &eb);
    const ds_u64 s = ds_sign(a) ^ ds_sign(b);
    if (ma == 0 || mb == 0) return s << 63;
    ds_i32 la = DS_CLZ64(ma) - 11, lb = DS_CLZ64(mb) - 11;     // subnormal significands -> 53 bits
    if (la > 0) { ma <<= la; ea -= la; }
    if (lb > 0) { mb <<= lb; eb -= lb; }
    const ds_u64 lo = ma * mb, hi = DS_MULHI64(ma, mb);       // 106-bit product, leading bit 104 or 105
    const ds_i32 top = 127 - DS_CLZ64(hi);
    const ds_i32 sh = top - 62;                                 // 42 or 43: leading bit -> 62
    ds_u64 mant = (hi << (64 - sh)) | (lo >> sh);
    const ds_u64 lost = lo & ((1ull << sh) - 1);
    mant |= (lost ? 1ull : 0ull);
    return ds_round_pack(s, (ds_i64) ea + eb + sh - 1065, mant);
}
// a / b, finite, b != 0, IEEE RNE (restoring division, 62 quotient bits + sticky)
DS_FN ds_u64 ds_div(ds_u64 a, ds_u64 b) {
    ds_u64 ma, mb; ds_i32 ea, eb;
    ds_unpack(a, &ma, &ea); ds_unpack(b, &mb, &eb);
    const ds_u64 s = ds_sign(a) ^ ds_sign(b);
    if (ma == 0) return s << 63;
    ds_i32 la = DS_CLZ64(ma) - 11, lb = DS_CLZ64(mb) - 11;
    if (la > 0) { ma <<= la; ea -= la; }
    if (lb > 0) { mb <<= lb; eb -= lb; }
    ds_u64 rem, q;                                              // integer part first so rem < mb
    if (ma >= mb) { rem = ma - mb; q = 1; } else { rem = ma; q = 0; }
    for (int i = 0; i < 62; i++) { rem <<= 1; q <<= 1; if (rem >= mb) { rem -= mb; q |= 1ull; } }
    q |= (rem ? 1ull : 0ull);                                   // sticky; q = floor(ma*2^62/mb) < 2^63
    return ds_round_pack(s, (ds_i64) ea - eb + 1023, q);
}
// any int64 -> double (RNE)
DS_FN ds_u64 ds_from_i64(ds_i64 v) {
    if (v == 0) return 0;
    const ds_u64 s = v < 0; const ds_u64 m = s ? (ds_u64) (-(v + 1)) + 1ull : (ds_u64) v;
    return ds_round_pack(s, 1085, m);                           // value = m * 2^(e - 1085)
}
// truncate toward zero to int64 (|x| < 2^63)
DS_FN ds_i64 ds_to_i64_trunc(ds_u64 a) {
    ds_u64 m; ds_i32 e; ds_unpack(a, &m, &e);
    if (m == 0) return 0;
    const ds_i32 k = e - 1075;                                  // value = m * 2^k
    ds_u64 mag;
    if (k >= 0) mag = (k >= 64) ? 0 : (m << k);
    else mag = (k <= -64) ? 0 : (m >> (-k));
    return ds_sign(a) ? -(ds_i64) mag : (ds_i64) mag;
}
// floor for |x| < 2^62, the reference's way: truncate toward zero, then correct
DS_FN ds_u64 ds_floor(ds_u64 a) {
    const ds_i64 t = ds_to_i64_trunc(a);
    ds_u64 r = ds_from_i64(t);
    if (ds_lt(a, r)) r = ds_from_i64(t - 1);
    return r;
}
#endif
// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// bp8_exact_soft.h — the b-posit8 W8A8 exact path (block scale, nearest encode, 256-bit quire
// accumulate, single readout) written on integers and det_soft.h's software double, so it
// compiles unchanged as C and as Metal Shading Language. Contract: bit-identical to
// ggml-cpu/quants.c and ggml-cuda/bposit8.cu. Gate: test_bp8_soft.c against libggml-cpu.
#ifndef BP8_EXACT_SOFT_H
#define BP8_EXACT_SOFT_H

#define BP8_ES    2
#define BP8_QFRAC 96
#define BP8_ZERO  0x00
#define BP8_NAR   0x80
#define BP8_QK    32
#define BP8_SS_LIMBS 20
#define BP8_SS_RADIX 352

#ifdef __METAL_VERSION__
#define BP8_PTR(T) thread T *
#define BP8_CPTR(T) const thread T *
#define BP8_TAB(T) constant T *
#define BP8_POPC32(x) ((int)metal::popcount((metal::uint)(x)))
#define BP8_CLZ32(x)  ((int)metal::clz((metal::uint)(x)))
#else
#define BP8_PTR(T) T *
#define BP8_CPTR(T) const T *
#define BP8_TAB(T) const T *
#define BP8_POPC32(x) __builtin_popcount((unsigned)(x))
#define BP8_CLZ32(x)  __builtin_clz((unsigned)(x))
#endif

// code -> M * 2^E (M = 0 for zero and NaR); mirrors ggml_bp8_code_to_ME
DS_FN void bp8_code_to_ME(ds_u32 p, BP8_PTR(ds_i32) M, BP8_PTR(ds_i32) E) {
    if (p == BP8_ZERO || p == BP8_NAR) { *M = 0; *E = 0; return; }
    const ds_i32 s = (p >> 7) & 1;
    ds_i32 rest = p & 0x7F;
    if (s) rest = ((~rest) + 1) & 0x7F;
    const ds_i32 leading = (rest >> 6) & 1;
    ds_i32 rs = 0;
    while (rs < 7 && ((rest >> (6 - rs)) & 1) == leading) rs++;
    ds_i32 k_reg, e = 0, fb = 0, fw = 0;
    if (rs == 7) {
        k_reg = leading ? 6 : -7;
    } else {
        k_reg = leading ? (rs - 1) : -rs;
        ds_i32 rem = 7 - (rs + 1);
        const ds_i32 r2 = rest & ((1 << rem) - 1);
        const ds_i32 ew = BP8_ES < rem ? BP8_ES : rem;
        if (ew > 0) { e = (r2 >> (rem - ew)) & ((1 << ew) - 1); e <<= (BP8_ES - ew); }
        rem -= ew; fw = rem; fb = fw > 0 ? (r2 & ((1 << fw) - 1)) : 0;
    }
    const ds_i32 m = (1 << fw) + fb;
    *M = s ? -m : m;
    *E = 4 * k_reg + e - fw;
}

// exact double bits of a code's value (M * 2^E)
DS_FN ds_u64 bp8_code_to_dbits(ds_u32 p) {
    ds_i32 M, E; bp8_code_to_ME(p, &M, &E);
    if (M == 0) return 0;
    return ds_ldexp(ds_from_i64_exact((ds_i64) M), E);
}

// exact block scale from float32 bit patterns; mirrors ggml_bp8_scale_exp_exact / CUDA
DS_FN ds_i32 bp8_scale_exp_exact_bits(BP8_CPTR(ds_u32) xb) {
    ds_u32 acc[BP8_SS_LIMBS];
    for (int i = 0; i < BP8_SS_LIMBS; i++) acc[i] = 0;
    int any = 0;
    for (int j = 0; j < BP8_QK; j++) {
        const ds_u32 f = xb[j];
        if ((f & 0x7FFFFFFFu) == 0) continue;
        const ds_i32 e = (f >> 23) & 0xFF; const ds_u64 mf = f & 0x7FFFFF;
        if (e == 0xFF) return 0;                                  // non-finite -> 0
        any = 1;
        ds_u64 mant; ds_i32 e2;
        if (e == 0) { mant = mf; e2 = -149; } else { mant = mf | 0x800000ull; e2 = e - 127 - 23; }
        const ds_u64 P = mant * mant;                             // <= 48 bits, exact
        const ds_i32 pos = 2 * e2 + BP8_SS_RADIX;                 // value = P * 2^(pos - RADIX)
        const ds_i32 w = pos >> 5, b = pos & 31;
        const ds_u64 lo = b ? (P << b) : P;
        const ds_u64 hi = b ? (P >> (64 - b)) : 0ull;
        ds_u32 parts[3]; parts[0] = (ds_u32) lo; parts[1] = (ds_u32) (lo >> 32); parts[2] = (ds_u32) hi;
        ds_u64 c = 0;
        for (int i = 0; i < 3; i++) { const ds_u64 t = (ds_u64) acc[w + i] + parts[i] + c; acc[w + i] = (ds_u32) t; c = t >> 32; }
        for (int i = w + 3; c && i < BP8_SS_LIMBS; i++) { const ds_u64 t = (ds_u64) acc[i] + c; acc[i] = (ds_u32) t; c = t >> 32; }
    }
    if (!any) return 0;
    ds_i32 top = -1, pop = 0;
    for (int i = BP8_SS_LIMBS - 1; i >= 0; i--) {
        if (acc[i]) { if (top < 0) top = 32 * i + 31 - BP8_CLZ32(acc[i]); pop += BP8_POPC32(acc[i]); }
    }
    const ds_i32 E = top - BP8_SS_RADIX - 5;
    ds_i32 se;
    if ((E & 1) == 0) se = E / 2;
    else { const ds_i32 n = (E - 1) / 2; se = (pop == 1) ? (((n & 1) == 0) ? n : n + 1) : n + 1; }
    return se > 127 ? 127 : (se < -128 ? -128 : se);
}

// nearest finite code to x (double bits); sv/sc = sorted value table (255). Mirrors the reference.
DS_FN ds_u32 bp8_encode_nearest_soft(ds_u64 x, BP8_TAB(ds_u64) sv, BP8_TAB(ds_u32) sc) {
    if ((x & 0x7FFFFFFFFFFFFFFFull) == 0) return BP8_ZERO;
    ds_i32 lo = 0, hi = 255;
    while (lo < hi) { const ds_i32 mid = (lo + hi) >> 1; if (ds_lt(sv[mid], x)) lo = mid + 1; else hi = mid; }
    ds_i32 best_k = -1; ds_u64 bestd = 0x7FF0000000000000ull;    // +inf
    const ds_i32 start = lo > 0 ? lo - 1 : lo, end = lo < 255 ? lo : lo - 1;
    for (ds_i32 k = start; k <= end; k++) {
        const ds_u64 d = ds_fabs(ds_sub(sv[k], x));
        if (ds_lt(d, bestd) || (ds_eq(d, bestd) && (best_k < 0 || sc[k] < sc[best_k]))) { bestd = d; best_k = k; }
    }
    if (best_k < 0 || !ds_lt(bestd, ds_fabs(x))) return BP8_ZERO;
    return sc[best_k];
}

// quantise one 32-float block (bit patterns in) -> scale_exp and 32 codes
DS_FN void bp8_quantize_block_soft(BP8_CPTR(ds_u32) xb, BP8_PTR(ds_i32) se_out, BP8_PTR(ds_u32) qs,
                                   BP8_TAB(ds_u64) sv, BP8_TAB(ds_u32) sc) {
    const ds_i32 se = bp8_scale_exp_exact_bits(xb);
    *se_out = se;
    for (int j = 0; j < BP8_QK; j++) {
        const ds_u64 x = ds_ldexp(ds_from_f32bits(xb[j]), -se);   // exact
        qs[j] = bp8_encode_nearest_soft(x, sv, sc);
    }
}

// lazily-carried limb accumulate (8 x int64 limbs), mirrors exact_lane_add
DS_FN void bp8_lane_add(BP8_PTR(ds_i64) a, ds_i64 P, ds_i32 sh) {
    if (sh >= 0) {
        const ds_i32 w = sh >> 5, bits = sh & 31;
        if (w < 8) {
            const ds_i64 V = P << bits;
            a[w] += (ds_i64) (ds_u32) V;
            if (w + 1 < 8) a[w + 1] += (V >> 32);
        }
    } else {
        const ds_i32 rs = -sh;
        const ds_i64 V = rs >= 63 ? (P < 0 ? -1 : 0) : (P >> rs);
        a[0] += V;
    }
}

// carry-normalise 8 int64 limbs into a 256-bit two's-complement word q[8]
DS_FN void bp8_limbs_to_q256(BP8_CPTR(ds_i64) a, BP8_PTR(ds_u32) q) {
    ds_i64 carry = 0;
    for (int w = 0; w < 8; w++) { const ds_i64 v = a[w] + carry; q[w] = (ds_u32) v; carry = v >> 32; }
}

// det_q256_to_double then round to float, on the software double
DS_FN ds_u32 bp8_q256_to_f32bits(BP8_CPTR(ds_u32) qin) {
    ds_u32 m[8]; for (int i = 0; i < 8; i++) m[i] = qin[i];
    const int neg = (m[7] >> 31) & 1;
    if (neg) { ds_u64 c = 1; for (int i = 0; i < 8; i++) { const ds_u64 v = (ds_u64) (~m[i]) + c; m[i] = (ds_u32) v; c = v >> 32; } }
    ds_u64 v = 0;
    for (int i = 7; i >= 0; i--) v = ds_add(ds_ldexp(v, 32), ds_from_u32(m[i]));
    v = ds_ldexp(v, -BP8_QFRAC);
    if (neg) v = ds_neg(v);
    return ds_to_f32bits(v);
}

// exact dot of two quantised rows (nblk blocks each) -> float bits; single-lane form
DS_FN ds_u32 bp8_dot_soft(BP8_CPTR(ds_i32) sex, BP8_CPTR(ds_u32) qx, BP8_CPTR(ds_i32) sey, BP8_CPTR(ds_u32) qy,
                          int nblk, BP8_TAB(ds_i32) tM, BP8_TAB(ds_i32) tE) {
    ds_i64 a[8]; for (int w = 0; w < 8; w++) a[w] = 0;
    for (int ib = 0; ib < nblk; ib++) {
        const ds_i32 se = sex[ib] + sey[ib] + BP8_QFRAC;
        for (int j = 0; j < BP8_QK; j++) {
            const ds_u32 cx = qx[ib * BP8_QK + j], cy = qy[ib * BP8_QK + j];
            const ds_i32 P = tM[cx] * tM[cy];
            if (P == 0) continue;
            bp8_lane_add(a, (ds_i64) P, tE[cx] + tE[cy] + se);
        }
    }
    ds_u32 q[8]; bp8_limbs_to_q256(a, q);
    return bp8_q256_to_f32bits(q);
}
#endif

#ifdef __METAL_VERSION__
constant ulong bp8_tab_sv[255] = {
    0xc170000000000000ul, 0xc130000000000000ul, 0xc110000000000000ul, 0xc0f0000000000000ul, 0xc0e0000000000000ul, 0xc0d0000000000000ul, 0xc0c0000000000000ul, 0xc0b0000000000000ul,
    0xc0a8000000000000ul, 0xc0a0000000000000ul, 0xc098000000000000ul, 0xc090000000000000ul, 0xc088000000000000ul, 0xc080000000000000ul, 0xc078000000000000ul, 0xc070000000000000ul,
    0xc06c000000000000ul, 0xc068000000000000ul, 0xc064000000000000ul, 0xc060000000000000ul, 0xc05c000000000000ul, 0xc058000000000000ul, 0xc054000000000000ul, 0xc050000000000000ul,
    0xc04c000000000000ul, 0xc048000000000000ul, 0xc044000000000000ul, 0xc040000000000000ul, 0xc03c000000000000ul, 0xc038000000000000ul, 0xc034000000000000ul, 0xc030000000000000ul,
    0xc02e000000000000ul, 0xc02c000000000000ul, 0xc02a000000000000ul, 0xc028000000000000ul, 0xc026000000000000ul, 0xc024000000000000ul, 0xc022000000000000ul, 0xc020000000000000ul,
    0xc01e000000000000ul, 0xc01c000000000000ul, 0xc01a000000000000ul, 0xc018000000000000ul, 0xc016000000000000ul, 0xc014000000000000ul, 0xc012000000000000ul, 0xc010000000000000ul,
    0xc00e000000000000ul, 0xc00c000000000000ul, 0xc00a000000000000ul, 0xc008000000000000ul, 0xc006000000000000ul, 0xc004000000000000ul, 0xc002000000000000ul, 0xc000000000000000ul,
    0xbffe000000000000ul, 0xbffc000000000000ul, 0xbffa000000000000ul, 0xbff8000000000000ul, 0xbff6000000000000ul, 0xbff4000000000000ul, 0xbff2000000000000ul, 0xbff0000000000000ul,
    0xbfee000000000000ul, 0xbfec000000000000ul, 0xbfea000000000000ul, 0xbfe8000000000000ul, 0xbfe6000000000000ul, 0xbfe4000000000000ul, 0xbfe2000000000000ul, 0xbfe0000000000000ul,
    0xbfde000000000000ul, 0xbfdc000000000000ul, 0xbfda000000000000ul, 0xbfd8000000000000ul, 0xbfd6000000000000ul, 0xbfd4000000000000ul, 0xbfd2000000000000ul, 0xbfd0000000000000ul,
    0xbfce000000000000ul, 0xbfcc000000000000ul, 0xbfca000000000000ul, 0xbfc8000000000000ul, 0xbfc6000000000000ul, 0xbfc4000000000000ul, 0xbfc2000000000000ul, 0xbfc0000000000000ul,
    0xbfbe000000000000ul, 0xbfbc000000000000ul, 0xbfba000000000000ul, 0xbfb8000000000000ul, 0xbfb6000000000000ul, 0xbfb4000000000000ul, 0xbfb2000000000000ul, 0xbfb0000000000000ul,
    0xbfac000000000000ul, 0xbfa8000000000000ul, 0xbfa4000000000000ul, 0xbfa0000000000000ul, 0xbf9c000000000000ul, 0xbf98000000000000ul, 0xbf94000000000000ul, 0xbf90000000000000ul,
    0xbf8c000000000000ul, 0xbf88000000000000ul, 0xbf84000000000000ul, 0xbf80000000000000ul, 0xbf7c000000000000ul, 0xbf78000000000000ul, 0xbf74000000000000ul, 0xbf70000000000000ul,
    0xbf68000000000000ul, 0xbf60000000000000ul, 0xbf58000000000000ul, 0xbf50000000000000ul, 0xbf48000000000000ul, 0xbf40000000000000ul, 0xbf38000000000000ul, 0xbf30000000000000ul,
    0xbf20000000000000ul, 0xbf10000000000000ul, 0xbf00000000000000ul, 0xbef0000000000000ul, 0xbed0000000000000ul, 0xbeb0000000000000ul, 0xbe70000000000000ul, 0x0000000000000000ul,
    0x3e70000000000000ul, 0x3eb0000000000000ul, 0x3ed0000000000000ul, 0x3ef0000000000000ul, 0x3f00000000000000ul, 0x3f10000000000000ul, 0x3f20000000000000ul, 0x3f30000000000000ul,
    0x3f38000000000000ul, 0x3f40000000000000ul, 0x3f48000000000000ul, 0x3f50000000000000ul, 0x3f58000000000000ul, 0x3f60000000000000ul, 0x3f68000000000000ul, 0x3f70000000000000ul,
    0x3f74000000000000ul, 0x3f78000000000000ul, 0x3f7c000000000000ul, 0x3f80000000000000ul, 0x3f84000000000000ul, 0x3f88000000000000ul, 0x3f8c000000000000ul, 0x3f90000000000000ul,
    0x3f94000000000000ul, 0x3f98000000000000ul, 0x3f9c000000000000ul, 0x3fa0000000000000ul, 0x3fa4000000000000ul, 0x3fa8000000000000ul, 0x3fac000000000000ul, 0x3fb0000000000000ul,
    0x3fb2000000000000ul, 0x3fb4000000000000ul, 0x3fb6000000000000ul, 0x3fb8000000000000ul, 0x3fba000000000000ul, 0x3fbc000000000000ul, 0x3fbe000000000000ul, 0x3fc0000000000000ul,
    0x3fc2000000000000ul, 0x3fc4000000000000ul, 0x3fc6000000000000ul, 0x3fc8000000000000ul, 0x3fca000000000000ul, 0x3fcc000000000000ul, 0x3fce000000000000ul, 0x3fd0000000000000ul,
    0x3fd2000000000000ul, 0x3fd4000000000000ul, 0x3fd6000000000000ul, 0x3fd8000000000000ul, 0x3fda000000000000ul, 0x3fdc000000000000ul, 0x3fde000000000000ul, 0x3fe0000000000000ul,
    0x3fe2000000000000ul, 0x3fe4000000000000ul, 0x3fe6000000000000ul, 0x3fe8000000000000ul, 0x3fea000000000000ul, 0x3fec000000000000ul, 0x3fee000000000000ul, 0x3ff0000000000000ul,
    0x3ff2000000000000ul, 0x3ff4000000000000ul, 0x3ff6000000000000ul, 0x3ff8000000000000ul, 0x3ffa000000000000ul, 0x3ffc000000000000ul, 0x3ffe000000000000ul, 0x4000000000000000ul,
    0x4002000000000000ul, 0x4004000000000000ul, 0x4006000000000000ul, 0x4008000000000000ul, 0x400a000000000000ul, 0x400c000000000000ul, 0x400e000000000000ul, 0x4010000000000000ul,
    0x4012000000000000ul, 0x4014000000000000ul, 0x4016000000000000ul, 0x4018000000000000ul, 0x401a000000000000ul, 0x401c000000000000ul, 0x401e000000000000ul, 0x4020000000000000ul,
    0x4022000000000000ul, 0x4024000000000000ul, 0x4026000000000000ul, 0x4028000000000000ul, 0x402a000000000000ul, 0x402c000000000000ul, 0x402e000000000000ul, 0x4030000000000000ul,
    0x4034000000000000ul, 0x4038000000000000ul, 0x403c000000000000ul, 0x4040000000000000ul, 0x4044000000000000ul, 0x4048000000000000ul, 0x404c000000000000ul, 0x4050000000000000ul,
    0x4054000000000000ul, 0x4058000000000000ul, 0x405c000000000000ul, 0x4060000000000000ul, 0x4064000000000000ul, 0x4068000000000000ul, 0x406c000000000000ul, 0x4070000000000000ul,
    0x4078000000000000ul, 0x4080000000000000ul, 0x4088000000000000ul, 0x4090000000000000ul, 0x4098000000000000ul, 0x40a0000000000000ul, 0x40a8000000000000ul, 0x40b0000000000000ul,
    0x40c0000000000000ul, 0x40d0000000000000ul, 0x40e0000000000000ul, 0x40f0000000000000ul, 0x4110000000000000ul, 0x4130000000000000ul, 0x4170000000000000ul
};
constant uint bp8_tab_sc[255] = {
    129, 130, 131, 132, 133, 134, 135, 136,
    137, 138, 139, 140, 141, 142, 143, 144,
    145, 146, 147, 148, 149, 150, 151, 152,
    153, 154, 155, 156, 157, 158, 159, 160,
    161, 162, 163, 164, 165, 166, 167, 168,
    169, 170, 171, 172, 173, 174, 175, 176,
    177, 178, 179, 180, 181, 182, 183, 184,
    185, 186, 187, 188, 189, 190, 191, 192,
    193, 194, 195, 196, 197, 198, 199, 200,
    201, 202, 203, 204, 205, 206, 207, 208,
    209, 210, 211, 212, 213, 214, 215, 216,
    217, 218, 219, 220, 221, 222, 223, 224,
    225, 226, 227, 228, 229, 230, 231, 232,
    233, 234, 235, 236, 237, 238, 239, 240,
    241, 242, 243, 244, 245, 246, 247, 248,
    249, 250, 251, 252, 253, 254, 255, 0,
    1, 2, 3, 4, 5, 6, 7, 8,
    9, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23, 24,
    25, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48,
    49, 50, 51, 52, 53, 54, 55, 56,
    57, 58, 59, 60, 61, 62, 63, 64,
    65, 66, 67, 68, 69, 70, 71, 72,
    73, 74, 75, 76, 77, 78, 79, 80,
    81, 82, 83, 84, 85, 86, 87, 88,
    89, 90, 91, 92, 93, 94, 95, 96,
    97, 98, 99, 100, 101, 102, 103, 104,
    105, 106, 107, 108, 109, 110, 111, 112,
    113, 114, 115, 116, 117, 118, 119, 120,
    121, 122, 123, 124, 125, 126, 127
};
constant int bp8_tab_M[256] = {
    0, 1, 1, 1, 1, 1, 1, 1,
    2, 3, 2, 3, 2, 3, 2, 3,
    4, 5, 6, 7, 4, 5, 6, 7,
    4, 5, 6, 7, 4, 5, 6, 7,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    4, 5, 6, 7, 4, 5, 6, 7,
    4, 5, 6, 7, 4, 5, 6, 7,
    2, 3, 2, 3, 2, 3, 2, 3,
    1, 1, 1, 1, 1, 1, 1, 1,
    0, -1, -1, -1, -1, -1, -1, -1,
    -1, -3, -2, -3, -2, -3, -2, -3,
    -2, -7, -6, -5, -4, -7, -6, -5,
    -4, -7, -6, -5, -4, -7, -6, -5,
    -4, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -7, -6, -5, -4, -7, -6, -5,
    -4, -7, -6, -5, -4, -7, -6, -5,
    -4, -3, -2, -3, -2, -3, -2, -3,
    -2, -1, -1, -1, -1, -1, -1, -1
};
constant int bp8_tab_E[256] = {
    0, -24, -20, -18, -16, -15, -14, -13,
    -13, -13, -12, -12, -11, -11, -10, -10,
    -10, -10, -10, -10, -9, -9, -9, -9,
    -8, -8, -8, -8, -7, -7, -7, -7,
    -7, -7, -7, -7, -7, -7, -7, -7,
    -6, -6, -6, -6, -6, -6, -6, -6,
    -5, -5, -5, -5, -5, -5, -5, -5,
    -4, -4, -4, -4, -4, -4, -4, -4,
    -3, -3, -3, -3, -3, -3, -3, -3,
    -2, -2, -2, -2, -2, -2, -2, -2,
    -1, -1, -1, -1, -1, -1, -1, -1,
    0, 0, 0, 0, 0, 0, 0, 0,
    2, 2, 2, 2, 3, 3, 3, 3,
    4, 4, 4, 4, 5, 5, 5, 5,
    7, 7, 8, 8, 9, 9, 10, 10,
    12, 13, 14, 15, 16, 18, 20, 24,
    0, 24, 20, 18, 16, 15, 14, 13,
    12, 10, 10, 9, 9, 8, 8, 7,
    7, 5, 5, 5, 5, 4, 4, 4,
    4, 3, 3, 3, 3, 2, 2, 2,
    2, 0, 0, 0, 0, 0, 0, 0,
    0, -1, -1, -1, -1, -1, -1, -1,
    -1, -2, -2, -2, -2, -2, -2, -2,
    -2, -3, -3, -3, -3, -3, -3, -3,
    -3, -4, -4, -4, -4, -4, -4, -4,
    -4, -5, -5, -5, -5, -5, -5, -5,
    -5, -6, -6, -6, -6, -6, -6, -6,
    -6, -7, -7, -7, -7, -7, -7, -7,
    -7, -7, -7, -7, -7, -8, -8, -8,
    -8, -9, -9, -9, -9, -10, -10, -10,
    -10, -10, -10, -11, -11, -12, -12, -13,
    -13, -13, -14, -15, -16, -18, -20, -24
};

#define BP8_NSG 4   // simdgroups (output rows) per threadgroup

// one thread per 32-element block of src1 (f32) -> block_bposit8, blocks laid out [i3][i2][i1][ib]
kernel void kernel_quantize_bposit8_f32(
        constant ggml_metal_kargs_bp8_quant & args,
        device const float * x,
        device block_bposit8 * y,
        uint tid [[thread_position_in_grid]]) {
    const long b = (long) tid;
    if (b >= args.nblk_total) return;
    const long ib = b % args.nblk_row;
    long r = b / args.nblk_row;
    const long i1 = r % args.ne1; r /= args.ne1;
    const long i2 = r % args.ne2;
    const long i3 = r / args.ne2;
    device const float * xr = x + i3 * args.s3 + i2 * args.s2 + i1 * args.s1 + ib * BP8_QK;
    uint xb[BP8_QK];
    for (int j = 0; j < BP8_QK; j++) xb[j] = as_type<uint>(xr[j]);
    int se; uint qs[BP8_QK];
    bp8_quantize_block_soft(xb, &se, qs, bp8_tab_sv, bp8_tab_sc);
    device block_bposit8 * yb = y + b;
    yb->scale_exp = (char) se;
    for (int j = 0; j < BP8_QK; j++) yb->qs[j] = (uchar) qs[j];
}

// exact dot: one simdgroup per output element; lanes stride the blocks; 8 int64 limbs per lane
// summed through threadgroup memory, carry-normalised once, read out through the software double
kernel void kernel_mul_mv_bposit8_exact(
        constant ggml_metal_kargs_bp8_mv & args,
        device const block_bposit8 * x,
        device const block_bposit8 * y,
        device float * dst,
        threadgroup long * red [[threadgroup(0)]],
        uint3  tgpig [[threadgroup_position_in_grid]],
        ushort tiisg [[thread_index_in_simdgroup]],
        ushort sgitg [[simdgroup_index_in_threadgroup]]) {
    const int  lane = tiisg;
    const long row  = (long) tgpig.x * BP8_NSG + sgitg;
    if (row >= args.ne01) return;                              // the whole simdgroup leaves together
    const long i1 = tgpig.y;
    const long i2 = tgpig.z % args.ne12, i3 = tgpig.z / args.ne12;
    device const block_bposit8 * xr = x + (i3 / args.r3) * args.s03 + (i2 / args.r2) * args.s02 + row * args.s01;
    device const block_bposit8 * yr = y + i3 * args.s13 + i2 * args.s12 + i1 * args.s11;
    long a[8];
    for (int w = 0; w < 8; w++) a[w] = 0;
    for (int ib = lane; ib < args.nblk; ib += 32) {
        const int se = (int) xr[ib].scale_exp + (int) yr[ib].scale_exp + BP8_QFRAC;
        for (int j = 0; j < BP8_QK; j++) {
            const uint cx = xr[ib].qs[j], cy = yr[ib].qs[j];
            const int P = bp8_tab_M[cx] * bp8_tab_M[cy];
            if (P == 0) continue;
            bp8_lane_add(a, (long) P, bp8_tab_E[cx] + bp8_tab_E[cy] + se);
        }
    }
    threadgroup long * r = red + ((int) sgitg * 32) * 8;
    for (int w = 0; w < 8; w++) r[lane * 8 + w] = a[w];
    metal::simdgroup_barrier(metal::mem_flags::mem_threadgroup);
    if (lane != 0) return;
    long s[8];
    for (int w = 0; w < 8; w++) { long t = 0; for (int l = 0; l < 32; l++) t += r[l * 8 + w]; s[w] = t; }
    uint q[8];
    bp8_limbs_to_q256(s, q);
    const uint out = bp8_q256_to_f32bits(q);
    dst[i3 * args.sd3 + i2 * args.sd2 + i1 * args.sd1 + row] = as_type<float>(out);
}
#endif // __METAL_VERSION__
#endif // GGML_METAL_BPOSIT8_H
