// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// ggml-metal-bposit8.h — GENERATED by ggml/src/ggml-metal/gen-bposit8-header.py from
// ggml/src/ggml-det/{det_soft.h,bp8_exact_soft.h,det_soft_ops.h}. Do not edit by hand. Self-contained: the Metal
// library embedder inlines it into ggml-metal.metal.
//
// b-posit8 W8A8 exact-quire matmul for Metal. Contract: every output float is bit-identical to
// the CPU kernel (ggml-cpu/quants.c) and to the CUDA kernel (ggml-cuda/bposit8.cu). Metal has no
// double, so the reference's double arithmetic (nearest-code encode, 256-bit -> double -> float
// readout) is performed by a software IEEE binary64 on 64-bit integers, gated against hardware
// double on 2e8 cases and against libggml-cpu on 3e5 rows (space-time/research/metal-exact).
#ifndef GGML_METAL_BPOSIT8_H
#define GGML_METAL_BPOSIT8_H
// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// det_soft.h — software IEEE-754 binary64 add/sub (round-to-nearest-even) and binary64 ->
// binary32 conversion on 64-bit integers, for targets without double (Metal). Written so the
// same text compiles as C and as Metal Shading Language: only fixed-width integers, no libm.
// Gate: research/metal-exact/test_det_soft.c compares every routine against hardware double.
#ifndef DET_SOFT_H
#define DET_SOFT_H

#ifdef __METAL_VERSION__
#define DS_FN static inline
#define DS_PTR(T) thread T *
#define DS_CLZ64(x) ((int)metal::clz((metal::ulong)(x)))
typedef ulong ds_u64; typedef long ds_i64; typedef uint ds_u32; typedef int ds_i32;   // after `using namespace metal;`
#else
#include <stdint.h>
#define DS_FN static inline
#define DS_PTR(T) T *
#define DS_CLZ64(x) __builtin_clzll((unsigned long long)(x))
typedef uint64_t ds_u64; typedef int64_t ds_i64; typedef uint32_t ds_u32; typedef int32_t ds_i32;
#endif

// ---- binary64 layout helpers (bits form) ----
DS_FN ds_u64 ds_sign(ds_u64 a) { return a >> 63; }
DS_FN ds_i32 ds_exp(ds_u64 a)  { return (ds_i32)((a >> 52) & 0x7FF); }
DS_FN ds_u64 ds_frac(ds_u64 a) { return a & 0xFFFFFFFFFFFFFull; }
DS_FN ds_u64 ds_pack(ds_u64 s, ds_i32 e, ds_u64 f) { return (s << 63) | ((ds_u64)e << 52) | f; }

// value = m * 2^(e - 52) with m the full significand (hidden bit set for normals); zero -> m=0
DS_FN void ds_unpack(ds_u64 a, DS_PTR(ds_u64) m, DS_PTR(ds_i32) e) {
    ds_i32 ex = ds_exp(a); ds_u64 f = ds_frac(a);
    if (ex == 0) { *m = f; *e = 1; }                 // subnormal or zero: exponent 1, no hidden bit
    else         { *m = f | (1ull << 52); *e = ex; }
}

// round a positive value given as (mant, e) where value = mant * 2^(e-52-EXTRA) with EXTRA
// guard bits below the 53-bit target, sticky already folded into bit 0 of mant.
// Returns packed bits (sign applied by caller). mant may exceed 53+EXTRA bits by one (carry).
#define DS_EXTRA 10
DS_FN ds_u64 ds_round_pack(ds_u64 s, ds_i64 e, ds_u64 mant) {
    if (mant == 0) return s << 63;
    // normalise so the leading bit is at position 52 + DS_EXTRA
    ds_i32 lz = DS_CLZ64(mant);
    ds_i32 want = 63 - (52 + DS_EXTRA);              // leading zeros wanted
    if (lz > want) { mant <<= (lz - want); e -= (lz - want); }
    else if (lz < want) {                            // shift right with sticky
        ds_i32 sh = want - lz;
        ds_u64 lost = mant & ((1ull << sh) - 1);
        mant = (mant >> sh) | (lost ? 1ull : 0ull);
        e += sh;
    }
    // subnormal handling: if e < 1, shift right further (with sticky) so exponent field is 0
    if (e < 1) {
        ds_i64 sh = 1 - e;
        if (sh > 63) { mant = (mant ? 1ull : 0ull); }
        else { ds_u64 lost = mant & ((1ull << sh) - 1); mant = (mant >> sh) | (lost ? 1ull : 0ull); }
        e = 1;
    }
    // round to nearest even on the DS_EXTRA guard bits
    ds_u64 guard = mant & ((1ull << DS_EXTRA) - 1);
    ds_u64 hmid  = 1ull << (DS_EXTRA - 1);
    ds_u64 q = mant >> DS_EXTRA;
    if (guard > hmid || (guard == hmid && (q & 1ull))) q += 1;
    if (q >> 53) { q >>= 1; e += 1; }                 // rounding carry
    if (e >= 0x7FF) return ds_pack(s, 0x7FF, 0);      // overflow -> inf
    if ((q >> 52) == 0) return ds_pack(s, 0, q);      // stayed subnormal (or zero)
    return ds_pack(s, (ds_i32)e, q & 0xFFFFFFFFFFFFFull);
}

// a + b, both finite, IEEE RNE. (No NaN/inf inputs in our uses; zeros handled.)
DS_FN ds_u64 ds_add(ds_u64 a, ds_u64 b) {
    ds_u64 ma, mb; ds_i32 ea, eb;
    ds_unpack(a, &ma, &ea); ds_unpack(b, &mb, &eb);
    ds_u64 sa = ds_sign(a), sb = ds_sign(b);
    if (ma == 0 && mb == 0) return (sa & sb) << 63;   // -0 + -0 = -0, else +0
    if (ma == 0) return b;
    if (mb == 0) return a;
    // make a the larger magnitude (by exponent then mantissa)
    if (ea < eb || (ea == eb && ma < mb)) { ds_u64 t = ma; ma = mb; mb = t; ds_i32 te = ea; ea = eb; eb = te; ds_u64 ts = sa; sa = sb; sb = ts; }
    ma <<= DS_EXTRA; mb <<= DS_EXTRA;                 // 63-bit working width
    ds_i32 d = ea - eb;
    if (d > 0) {
        if (d >= 64) mb = (mb ? 1ull : 0ull);
        else { ds_u64 lost = mb & ((1ull << d) - 1); mb = (mb >> d) | (lost ? 1ull : 0ull); }
    }
    ds_u64 mant;
    if (sa == sb) mant = ma + mb; else mant = ma - mb; // ma >= mb by construction
    if (mant == 0) return 0;                          // exact cancellation -> +0 (RNE)
    return ds_round_pack(sa, ea, mant);
}
DS_FN ds_u64 ds_neg(ds_u64 a) { return a ^ (1ull << 63); }
DS_FN ds_u64 ds_sub(ds_u64 a, ds_u64 b) { return ds_add(a, ds_neg(b)); }
DS_FN ds_u64 ds_fabs(ds_u64 a) { return a & 0x7FFFFFFFFFFFFFFFull; }
// ordering of finite doubles (no NaN): a < b
DS_FN ds_i64 ds_key(ds_u64 a) { return (a >> 63) ? -(ds_i64)(a & 0x7FFFFFFFFFFFFFFFull) : (ds_i64)a; }
DS_FN int ds_lt(ds_u64 a, ds_u64 b) { return ds_key(a) < ds_key(b); }
DS_FN int ds_eq(ds_u64 a, ds_u64 b) { return ds_key(a) == ds_key(b); }
// exact scaling by 2^k (no overflow in our uses; underflow to subnormal handled by repack)
DS_FN ds_u64 ds_ldexp(ds_u64 a, ds_i32 k) {
    ds_u64 m; ds_i32 e; ds_unpack(a, &m, &e);
    if (m == 0) return a;
    return ds_round_pack(ds_sign(a), (ds_i64)e + k, m << DS_EXTRA);
}
// exact conversions
DS_FN ds_u64 ds_from_u32(ds_u32 v) { return v ? ds_round_pack(0, 1075, ((ds_u64)v) << DS_EXTRA) : 0; }   // e biased: value = m*2^(e-1075)
DS_FN ds_u64 ds_from_i64_exact(ds_i64 v) {        // |v| < 2^53 assumed exact
    ds_u64 s = v < 0; ds_u64 m = s ? (ds_u64)(-v) : (ds_u64)v;
    return m ? ds_round_pack(s, 1075, m << DS_EXTRA) : 0;
}
// float32 bits -> exact binary64 bits (finite inputs)
DS_FN ds_u64 ds_from_f32bits(ds_u32 f) {
    ds_u64 s = f >> 31; ds_i32 e = (f >> 23) & 0xFF; ds_u64 m = f & 0x7FFFFF;
    if (e == 0) { if (m == 0) return s << 63; return ds_round_pack(s, 1 - 127 + 1023 - 23 + 52, m << DS_EXTRA); }
    return ds_round_pack(s, (ds_i64)e - 127 + 1023, (m | 0x800000ull) << (29 + DS_EXTRA));
}
// binary64 -> binary32 bits, RNE, with subnormal floats and overflow to inf
DS_FN ds_u32 ds_to_f32bits(ds_u64 a) {
    ds_u64 s = ds_sign(a); ds_u64 m; ds_i32 e; ds_unpack(a, &m, &e);
    if (m == 0) return (ds_u32)(s << 31);
    ds_i32 lz = DS_CLZ64(m);                          // normalise leading bit to 52 for subnormal doubles
    if (lz > 11) { m <<= (lz - 11); e -= (lz - 11); }
    ds_i64 fe = (ds_i64)e - 1023 + 127;               // float exponent field candidate
    // keep 24 bits + guard: shift m (53 bits) right by 29 with sticky -> q has 24 bits + we need RNE
    ds_i32 sh = 29;
    if (fe < 1) { sh += (ds_i32)(1 - fe); fe = 1; }   // float subnormal: denormalise
    ds_u64 q, lost, hmid;
    if (sh > 64) return (ds_u32)(s << 31);                       // below hmid the smallest subnormal
    if (sh == 64) { q = 0; lost = m; hmid = 1ull << 63; }
    else { q = m >> sh; lost = m & ((1ull << sh) - 1); hmid = 1ull << (sh - 1); }
    if (lost > hmid || (lost == hmid && (q & 1ull))) q += 1;
    if (q >> 24) { q >>= 1; fe += 1; }
    if (fe >= 0xFF) return (ds_u32)((s << 31) | 0x7F800000u);
    if ((q >> 23) == 0) return (ds_u32)((s << 31) | (ds_u32)q);   // subnormal float (or zero)
    return (ds_u32)((s << 31) | ((ds_u32)fe << 23) | ((ds_u32)q & 0x7FFFFFu));
}

// ---- multiply, divide, floor, integer conversions (for the norm / softmax / rope ports) ----
#ifdef __METAL_VERSION__
#define DS_MULHI64(a, b) ((ds_u64)metal::mulhi((ulong)(a), (ulong)(b)))
#else
#define DS_MULHI64(a, b) ((ds_u64)(((unsigned __int128)(a) * (unsigned __int128)(b)) >> 64))
#endif
// a * b, finite inputs, IEEE RNE
DS_FN ds_u64 ds_mul(ds_u64 a, ds_u64 b) {
    ds_u64 ma, mb; ds_i32 ea, eb;
    ds_unpack(a, &ma, &ea); ds_unpack(b, &mb, &eb);
    const ds_u64 s = ds_sign(a) ^ ds_sign(b);
    if (ma == 0 || mb == 0) return s << 63;
    ds_i32 la = DS_CLZ64(ma) - 11, lb = DS_CLZ64(mb) - 11;     // subnormal significands -> 53 bits
    if (la > 0) { ma <<= la; ea -= la; }
    if (lb > 0) { mb <<= lb; eb -= lb; }
    const ds_u64 lo = ma * mb, hi = DS_MULHI64(ma, mb);       // 106-bit product, leading bit 104 or 105
    const ds_i32 top = 127 - DS_CLZ64(hi);
    const ds_i32 sh = top - 62;                                 // 42 or 43: leading bit -> 62
    ds_u64 mant = (hi << (64 - sh)) | (lo >> sh);
    const ds_u64 lost = lo & ((1ull << sh) - 1);
    mant |= (lost ? 1ull : 0ull);
    return ds_round_pack(s, (ds_i64) ea + eb + sh - 1065, mant);
}
// a / b, finite, b != 0, IEEE RNE (restoring division, 62 quotient bits + sticky)
DS_FN ds_u64 ds_div(ds_u64 a, ds_u64 b) {
    ds_u64 ma, mb; ds_i32 ea, eb;
    ds_unpack(a, &ma, &ea); ds_unpack(b, &mb, &eb);
    const ds_u64 s = ds_sign(a) ^ ds_sign(b);
    if (ma == 0) return s << 63;
    ds_i32 la = DS_CLZ64(ma) - 11, lb = DS_CLZ64(mb) - 11;
    if (la > 0) { ma <<= la; ea -= la; }
    if (lb > 0) { mb <<= lb; eb -= lb; }
    ds_u64 rem, q;                                              // integer part first so rem < mb
    if (ma >= mb) { rem = ma - mb; q = 1; } else { rem = ma; q = 0; }
    for (int i = 0; i < 62; i++) { rem <<= 1; q <<= 1; if (rem >= mb) { rem -= mb; q |= 1ull; } }
    q |= (rem ? 1ull : 0ull);                                   // sticky; q = floor(ma*2^62/mb) < 2^63
    return ds_round_pack(s, (ds_i64) ea - eb + 1023, q);
}
// any int64 -> double (RNE)
DS_FN ds_u64 ds_from_i64(ds_i64 v) {
    if (v == 0) return 0;
    const ds_u64 s = v < 0; const ds_u64 m = s ? (ds_u64) (-(v + 1)) + 1ull : (ds_u64) v;
    return ds_round_pack(s, 1085, m);                           // value = m * 2^(e - 1085)
}
// truncate toward zero to int64 (|x| < 2^63)
DS_FN ds_i64 ds_to_i64_trunc(ds_u64 a) {
    ds_u64 m; ds_i32 e; ds_unpack(a, &m, &e);
    if (m == 0) return 0;
    const ds_i32 k = e - 1075;                                  // value = m * 2^k
    ds_u64 mag;
    if (k >= 0) mag = (k >= 64) ? 0 : (m << k);
    else mag = (k <= -64) ? 0 : (m >> (-k));
    return ds_sign(a) ? -(ds_i64) mag : (ds_i64) mag;
}
// floor for |x| < 2^62, the reference's way: truncate toward zero, then correct
DS_FN ds_u64 ds_floor(ds_u64 a) {
    const ds_i64 t = ds_to_i64_trunc(a);
    ds_u64 r = ds_from_i64(t);
    if (ds_lt(a, r)) r = ds_from_i64(t - 1);
    return r;
}
#endif
// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// bp8_exact_soft.h — the b-posit8 W8A8 exact path (block scale, nearest encode, 256-bit quire
// accumulate, single readout) written on integers and det_soft.h's software double, so it
// compiles unchanged as C and as Metal Shading Language. Contract: bit-identical to
// ggml-cpu/quants.c and ggml-cuda/bposit8.cu. Gate: test_bp8_soft.c against libggml-cpu.
#ifndef BP8_EXACT_SOFT_H
#define BP8_EXACT_SOFT_H

#define BP8_ES    2
#define BP8_QFRAC 96
#define BP8_ZERO  0x00
#define BP8_NAR   0x80
#define BP8_QK    32
#define BP8_SS_LIMBS 20
#define BP8_SS_RADIX 352

#ifdef __METAL_VERSION__
#define BP8_PTR(T) thread T *
#define BP8_CPTR(T) const thread T *
#define BP8_TAB(T) constant T *
#define BP8_POPC32(x) ((int)metal::popcount((metal::uint)(x)))
#define BP8_CLZ32(x)  ((int)metal::clz((metal::uint)(x)))
#else
#define BP8_PTR(T) T *
#define BP8_CPTR(T) const T *
#define BP8_TAB(T) const T *
#define BP8_POPC32(x) __builtin_popcount((unsigned)(x))
#define BP8_CLZ32(x)  __builtin_clz((unsigned)(x))
#endif

// code -> M * 2^E (M = 0 for zero and NaR); mirrors ggml_bp8_code_to_ME
DS_FN void bp8_code_to_ME(ds_u32 p, BP8_PTR(ds_i32) M, BP8_PTR(ds_i32) E) {
    if (p == BP8_ZERO || p == BP8_NAR) { *M = 0; *E = 0; return; }
    const ds_i32 s = (p >> 7) & 1;
    ds_i32 rest = p & 0x7F;
    if (s) rest = ((~rest) + 1) & 0x7F;
    const ds_i32 leading = (rest >> 6) & 1;
    ds_i32 rs = 0;
    while (rs < 7 && ((rest >> (6 - rs)) & 1) == leading) rs++;
    ds_i32 k_reg, e = 0, fb = 0, fw = 0;
    if (rs == 7) {
        k_reg = leading ? 6 : -7;
    } else {
        k_reg = leading ? (rs - 1) : -rs;
        ds_i32 rem = 7 - (rs + 1);
        const ds_i32 r2 = rest & ((1 << rem) - 1);
        const ds_i32 ew = BP8_ES < rem ? BP8_ES : rem;
        if (ew > 0) { e = (r2 >> (rem - ew)) & ((1 << ew) - 1); e <<= (BP8_ES - ew); }
        rem -= ew; fw = rem; fb = fw > 0 ? (r2 & ((1 << fw) - 1)) : 0;
    }
    const ds_i32 m = (1 << fw) + fb;
    *M = s ? -m : m;
    *E = 4 * k_reg + e - fw;
}

// exact double bits of a code's value (M * 2^E)
DS_FN ds_u64 bp8_code_to_dbits(ds_u32 p) {
    ds_i32 M, E; bp8_code_to_ME(p, &M, &E);
    if (M == 0) return 0;
    return ds_ldexp(ds_from_i64_exact((ds_i64) M), E);
}

// exact block scale from float32 bit patterns; mirrors ggml_bp8_scale_exp_exact / CUDA
DS_FN ds_i32 bp8_scale_exp_exact_bits(BP8_CPTR(ds_u32) xb) {
    ds_u32 acc[BP8_SS_LIMBS];
    for (int i = 0; i < BP8_SS_LIMBS; i++) acc[i] = 0;
    int any = 0;
    for (int j = 0; j < BP8_QK; j++) {
        const ds_u32 f = xb[j];
        if ((f & 0x7FFFFFFFu) == 0) continue;
        const ds_i32 e = (f >> 23) & 0xFF; const ds_u64 mf = f & 0x7FFFFF;
        if (e == 0xFF) return 0;                                  // non-finite -> 0
        any = 1;
        ds_u64 mant; ds_i32 e2;
        if (e == 0) { mant = mf; e2 = -149; } else { mant = mf | 0x800000ull; e2 = e - 127 - 23; }
        const ds_u64 P = mant * mant;                             // <= 48 bits, exact
        const ds_i32 pos = 2 * e2 + BP8_SS_RADIX;                 // value = P * 2^(pos - RADIX)
        const ds_i32 w = pos >> 5, b = pos & 31;
        const ds_u64 lo = b ? (P << b) : P;
        const ds_u64 hi = b ? (P >> (64 - b)) : 0ull;
        ds_u32 parts[3]; parts[0] = (ds_u32) lo; parts[1] = (ds_u32) (lo >> 32); parts[2] = (ds_u32) hi;
        ds_u64 c = 0;
        for (int i = 0; i < 3; i++) { const ds_u64 t = (ds_u64) acc[w + i] + parts[i] + c; acc[w + i] = (ds_u32) t; c = t >> 32; }
        for (int i = w + 3; c && i < BP8_SS_LIMBS; i++) { const ds_u64 t = (ds_u64) acc[i] + c; acc[i] = (ds_u32) t; c = t >> 32; }
    }
    if (!any) return 0;
    ds_i32 top = -1, pop = 0;
    for (int i = BP8_SS_LIMBS - 1; i >= 0; i--) {
        if (acc[i]) { if (top < 0) top = 32 * i + 31 - BP8_CLZ32(acc[i]); pop += BP8_POPC32(acc[i]); }
    }
    const ds_i32 E = top - BP8_SS_RADIX - 5;
    ds_i32 se;
    if ((E & 1) == 0) se = E / 2;
    else { const ds_i32 n = (E - 1) / 2; se = (pop == 1) ? (((n & 1) == 0) ? n : n + 1) : n + 1; }
    return se > 127 ? 127 : (se < -128 ? -128 : se);
}

// nearest finite code to x (double bits); sv/sc = sorted value table (255). Mirrors the reference.
DS_FN ds_u32 bp8_encode_nearest_soft(ds_u64 x, BP8_TAB(ds_u64) sv, BP8_TAB(ds_u32) sc) {
    if ((x & 0x7FFFFFFFFFFFFFFFull) == 0) return BP8_ZERO;
    ds_i32 lo = 0, hi = 255;
    while (lo < hi) { const ds_i32 mid = (lo + hi) >> 1; if (ds_lt(sv[mid], x)) lo = mid + 1; else hi = mid; }
    ds_i32 best_k = -1; ds_u64 bestd = 0x7FF0000000000000ull;    // +inf
    const ds_i32 start = lo > 0 ? lo - 1 : lo, end = lo < 255 ? lo : lo - 1;
    for (ds_i32 k = start; k <= end; k++) {
        const ds_u64 d = ds_fabs(ds_sub(sv[k], x));
        if (ds_lt(d, bestd) || (ds_eq(d, bestd) && (best_k < 0 || sc[k] < sc[best_k]))) { bestd = d; best_k = k; }
    }
    if (best_k < 0 || !ds_lt(bestd, ds_fabs(x))) return BP8_ZERO;
    return sc[best_k];
}

// quantise one 32-float block (bit patterns in) -> scale_exp and 32 codes
DS_FN void bp8_quantize_block_soft(BP8_CPTR(ds_u32) xb, BP8_PTR(ds_i32) se_out, BP8_PTR(ds_u32) qs,
                                   BP8_TAB(ds_u64) sv, BP8_TAB(ds_u32) sc) {
    const ds_i32 se = bp8_scale_exp_exact_bits(xb);
    *se_out = se;
    for (int j = 0; j < BP8_QK; j++) {
        const ds_u64 x = ds_ldexp(ds_from_f32bits(xb[j]), -se);   // exact
        qs[j] = bp8_encode_nearest_soft(x, sv, sc);
    }
}

// lazily-carried limb accumulate (8 x int64 limbs), mirrors exact_lane_add
DS_FN void bp8_lane_add(BP8_PTR(ds_i64) a, ds_i64 P, ds_i32 sh) {
    if (sh >= 0) {
        const ds_i32 w = sh >> 5, bits = sh & 31;
        if (w < 8) {
            const ds_i64 V = P << bits;
            a[w] += (ds_i64) (ds_u32) V;
            if (w + 1 < 8) a[w + 1] += (V >> 32);
        }
    } else {
        const ds_i32 rs = -sh;
        const ds_i64 V = rs >= 63 ? (P < 0 ? -1 : 0) : (P >> rs);
        a[0] += V;
    }
}

// carry-normalise 8 int64 limbs into a 256-bit two's-complement word q[8]
DS_FN void bp8_limbs_to_q256(BP8_CPTR(ds_i64) a, BP8_PTR(ds_u32) q) {
    ds_i64 carry = 0;
    for (int w = 0; w < 8; w++) { const ds_i64 v = a[w] + carry; q[w] = (ds_u32) v; carry = v >> 32; }
}

// det_q256_to_double then round to float, on the software double
DS_FN ds_u32 bp8_q256_to_f32bits(BP8_CPTR(ds_u32) qin) {
    ds_u32 m[8]; for (int i = 0; i < 8; i++) m[i] = qin[i];
    const int neg = (m[7] >> 31) & 1;
    if (neg) { ds_u64 c = 1; for (int i = 0; i < 8; i++) { const ds_u64 v = (ds_u64) (~m[i]) + c; m[i] = (ds_u32) v; c = v >> 32; } }
    ds_u64 v = 0;
    for (int i = 7; i >= 0; i--) v = ds_add(ds_ldexp(v, 32), ds_from_u32(m[i]));
    v = ds_ldexp(v, -BP8_QFRAC);
    if (neg) v = ds_neg(v);
    return ds_to_f32bits(v);
}

// exact dot of two quantised rows (nblk blocks each) -> float bits; single-lane form
DS_FN ds_u32 bp8_dot_soft(BP8_CPTR(ds_i32) sex, BP8_CPTR(ds_u32) qx, BP8_CPTR(ds_i32) sey, BP8_CPTR(ds_u32) qy,
                          int nblk, BP8_TAB(ds_i32) tM, BP8_TAB(ds_i32) tE) {
    ds_i64 a[8]; for (int w = 0; w < 8; w++) a[w] = 0;
    for (int ib = 0; ib < nblk; ib++) {
        const ds_i32 se = sex[ib] + sey[ib] + BP8_QFRAC;
        for (int j = 0; j < BP8_QK; j++) {
            const ds_u32 cx = qx[ib * BP8_QK + j], cy = qy[ib * BP8_QK + j];
            const ds_i32 P = tM[cx] * tM[cy];
            if (P == 0) continue;
            bp8_lane_add(a, (ds_i64) P, tE[cx] + tE[cy] + se);
        }
    }
    ds_u32 q[8]; bp8_limbs_to_q256(a, q);
    return bp8_q256_to_f32bits(q);
}
#endif
// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// det_soft_ops.h — GENERATED by gen_det_soft_ops.py. ggml-det.h's exact-profile routines that use
// double, rewritten on det_soft.h (software binary64 on integers) so they run where there is no
// double (Metal). Operation order is the reference's, so results are bit-identical.
// Constants are the exact bit patterns of the reference's literals.
#ifndef DET_SOFT_OPS_H
#define DET_SOFT_OPS_H

#ifdef __METAL_VERSION__
#define DSO_F2B(x) as_type<uint>(x)
#define DSO_B2F(b) as_type<float>(b)
#define DSO_CONST constant
#define DSO_TAB(T) constant T *
#else
#include <string.h>
#include <math.h>
DS_FN ds_u32 DSO_F2B(float x) { ds_u32 b; memcpy(&b, &x, 4); return b; }
DS_FN float  DSO_B2F(ds_u32 b) { float x; memcpy(&x, &b, 4); return x; }
#define DSO_CONST static const
#define DSO_TAB(T) const T *
#endif

// ---- software binary32 ops (IEEE RNE incl. subnormals, inf, nan) on the software double ----
// Apple GPUs flush single-precision subnormals to zero (measured on the M4 Pro with
// MTLMathModeSafe and fp contract off), so on Metal every float op of the exact profile goes
// through these; the double has >= 2*24+2 bits, so one double op + one rounding is the correctly
// rounded float op (Figueroa). On the host they are only compiled for the gate (test_det_ops.c).
#define DSO_QNAN 0x7FC00000u
DS_FN int dso_f_is_nan(ds_u32 b) { return ((b & 0x7F800000u) == 0x7F800000u) && (b & 0x7FFFFFu); }
DS_FN int dso_f_is_inf(ds_u32 b) { return (b & 0x7FFFFFFFu) == 0x7F800000u; }
DS_FN int dso_f_is_zero(ds_u32 b) { return (b & 0x7FFFFFFFu) == 0u; }
DS_FN ds_u32 dso_fmul_bits(ds_u32 a, ds_u32 b) {
    const ds_u32 s = (a ^ b) & 0x80000000u;
    if (dso_f_is_nan(a) || dso_f_is_nan(b)) return DSO_QNAN;
    if (dso_f_is_inf(a) || dso_f_is_inf(b)) return (dso_f_is_zero(a) || dso_f_is_zero(b)) ? DSO_QNAN : (s | 0x7F800000u);
    return ds_to_f32bits(ds_mul(ds_from_f32bits(a), ds_from_f32bits(b)));
}
DS_FN ds_u32 dso_fadd_bits(ds_u32 a, ds_u32 b) {
    if (dso_f_is_nan(a) || dso_f_is_nan(b)) return DSO_QNAN;
    if (dso_f_is_inf(a)) return (dso_f_is_inf(b) && (a != b)) ? DSO_QNAN : a;
    if (dso_f_is_inf(b)) return b;
    if (dso_f_is_zero(a) && dso_f_is_zero(b)) return (a == b) ? a : 0u;   // (+0)+(-0) = +0 in RNE
    return ds_to_f32bits(ds_add(ds_from_f32bits(a), ds_from_f32bits(b)));
}
DS_FN ds_u32 dso_fsub_bits(ds_u32 a, ds_u32 b) { return dso_fadd_bits(a, b ^ 0x80000000u); }
DS_FN ds_u32 dso_fdiv_bits(ds_u32 a, ds_u32 b) {
    const ds_u32 s = (a ^ b) & 0x80000000u;
    if (dso_f_is_nan(a) || dso_f_is_nan(b)) return DSO_QNAN;
    if (dso_f_is_inf(a)) return dso_f_is_inf(b) ? DSO_QNAN : (s | 0x7F800000u);
    if (dso_f_is_inf(b)) return s;
    if (dso_f_is_zero(b)) return dso_f_is_zero(a) ? DSO_QNAN : (s | 0x7F800000u);
    if (dso_f_is_zero(a)) return s;
    return ds_to_f32bits(ds_div(ds_from_f32bits(a), ds_from_f32bits(b)));
}
// sqrt: integer square root of the significand with 27+ result bits and a sticky remainder;
// never a tie (an exact 25-bit odd root would need an odd radicand of 49+ bits)
DS_FN ds_u32 dso_fsqrt_bits(ds_u32 a) {
    if (dso_f_is_nan(a)) return DSO_QNAN;
    if (dso_f_is_zero(a)) return a;
    if (a & 0x80000000u) return DSO_QNAN;
    if (dso_f_is_inf(a)) return a;
    ds_i32 e = (ds_i32) ((a >> 23) & 0xFF); ds_u64 m = a & 0x7FFFFFu;
    if (e == 0) { e = 1; while (!(m & 0x800000u)) { m <<= 1; e--; } } else { m |= 0x800000u; }
    ds_i32 e2 = e - 127 - 23;                       // value = m * 2^e2
    if (e2 & 1) { m <<= 1; e2--; }                   // even exponent
    const ds_u64 N = m << 30;                        // root has 27 or 28 bits
    ds_u64 q = 0, r = 0;
    for (ds_i32 i = 31; i >= 0; i--) {               // restoring integer sqrt, 2 radicand bits per step
        r = (r << 2) | ((N >> (2 * i)) & 3u);
        const ds_u64 t = (q << 2) | 1u;
        q <<= 1;
        if (r >= t) { r -= t; q |= 1u; }
    }
    // q = floor(sqrt(N)), sticky = r != 0; result = q * 2^(e2/2 - 15)
    ds_i32 qb = 64 - DS_CLZ64(q);                    // 27 or 28
    const ds_i32 sh = qb - 24;
    ds_u64 mant = q >> sh;
    const ds_u64 rem = q & ((1ull << sh) - 1), hmid = 1ull << (sh - 1);
    if (rem > hmid || (rem == hmid && (r != 0 || (mant & 1u)))) { mant++; if (mant == (1ull << 24)) { mant >>= 1; qb++; } }
    const ds_i32 ef = (e2 / 2 - 15) + (qb - 24) + 23 + 127;   // biased float exponent of mant * 2^(...)
    return (ds_u32) (((ds_u32) ef << 23) | (ds_u32) (mant & 0x7FFFFFu));
}
// MAX(a, b) = (a > b) ? a : b on the total order of the bits (+0 > -0; both give the same softmax)
DS_FN ds_u32 dso_fkey(ds_u32 b) { return (b & 0x80000000u) ? ~b : (b | 0x80000000u); }
DS_FN ds_u32 dso_funkey(ds_u32 k) { return (k & 0x80000000u) ? (k & 0x7FFFFFFFu) : ~k; }   // inverse of dso_fkey
DS_FN ds_u32 dso_fmax_bits(ds_u32 a, ds_u32 b) { return dso_fkey(a) > dso_fkey(b) ? a : b; }
// binary16 bits -> binary32 bits, exact (subnormal halves normalised in integers)
DS_FN ds_u32 dso_f16_to_f32bits(ds_u32 h) {
    const ds_u32 s = (h >> 15) & 1u, e = (h >> 10) & 0x1Fu; ds_u32 f = h & 0x3FFu;
    if (e == 0) {
        if (f == 0) return s << 31;
        ds_u32 ee = 1; while (!(f & 0x400u)) { f <<= 1; ee--; }
        return (s << 31) | ((ee + 112u) << 23) | ((f & 0x3FFu) << 13);
    }
    if (e == 31) return (s << 31) | 0x7F800000u | (f << 13);
    return (s << 31) | ((e + 112u) << 23) | (f << 13);
}
#ifdef __METAL_VERSION__
DS_FN float dso_fmul(float a, float b) { return DSO_B2F(dso_fmul_bits(DSO_F2B(a), DSO_F2B(b))); }
DS_FN float dso_fadd(float a, float b) { return DSO_B2F(dso_fadd_bits(DSO_F2B(a), DSO_F2B(b))); }
DS_FN float dso_fsub(float a, float b) { return DSO_B2F(dso_fsub_bits(DSO_F2B(a), DSO_F2B(b))); }
DS_FN float dso_fdiv(float a, float b) { return DSO_B2F(dso_fdiv_bits(DSO_F2B(a), DSO_F2B(b))); }
DS_FN float dso_fsqrt(float a)         { return DSO_B2F(dso_fsqrt_bits(DSO_F2B(a))); }
#define DSO_FMUL(a, b) dso_fmul((a), (b))
#define DSO_FADD(a, b) dso_fadd((a), (b))
#define DSO_FSUB(a, b) dso_fsub((a), (b))
#define DSO_FDIV(a, b) dso_fdiv((a), (b))
#define DSO_FSQRT(a)   dso_fsqrt(a)
#else
#define DSO_FMUL(a, b) ((a) * (b))
#define DSO_FADD(a, b) ((a) + (b))
#define DSO_FSUB(a, b) ((a) - (b))
#define DSO_FDIV(a, b) ((a) / (b))
#define DSO_FSQRT(a)   sqrtf(a)
#endif

// double constants (bit patterns)
#define DSO_ZERO 0x0000000000000000ull
#define DSO_HALF 0x3fe0000000000000ull
#define DSO_ONE  0x3ff0000000000000ull
#define DSO_TWO  0x4000000000000000ull
#define DSO_M2   0xc000000000000000ull
#define DSO_INV_LN2 0x3ff71547652b82feull
#define DSO_LN2_HI  0x3fe62e42fee00000ull
#define DSO_LN2_LO  0x3dea39ef35793c76ull
#define DSO_LN2     0x3fe62e42fefa39efull
#define DSO_SQRT1_2 0x3ff6a09e667f3bcdull
#define DSO_TWO_OVER_PI 0x3fe45f306dc9c883ull
#define DSO_PIO2_1 0x3ff921fb54400000ull
#define DSO_PIO2_2 0x3dd0b4611a626331ull
#define DSO_PIO2_3 0x3ba3198a2e037073ull
#define DSO_TWENTY 0x4034000000000000ull
#define DSO_M_TWENTY 0xc034000000000000ull
#define DSO_INF 0x7FF0000000000000ull

// coefficient tables at program scope (MSL forbids address-space-qualified automatics)
DSO_CONST ds_u64 dso_expc[14] = { 0x3ff0000000000000ull, 0x3ff0000000000000ull, 0x3fe0000000000000ull, 0x3fc5555555555555ull, 0x3fa5555555555555ull, 0x3f81111111111111ull, 0x3f56c16c16c16c17ull, 0x3f2a01a01a01a01aull, 0x3efa01a01a01a01aull, 0x3ec71de3a556c734ull, 0x3e927e4fb7789f5cull, 0x3e5ae64567f544e4ull, 0x3e21eed8eff8d898ull, 0x3de6124613a86d09ull };
DSO_CONST ds_u64 dso_invk[15] = { 0x3ff0000000000000ull, 0x3fd5555555555555ull, 0x3fc999999999999aull, 0x3fc2492492492492ull, 0x3fbc71c71c71c71cull, 0x3fb745d1745d1746ull, 0x3fb3b13b13b13b14ull, 0x3fb1111111111111ull, 0x3fae1e1e1e1e1e1eull, 0x3faaf286bca1af28ull, 0x3fa8618618618618ull, 0x3fa642c8590b2164ull, 0x3fa47ae147ae147bull, 0x3fa2f684bda12f68ull, 0x3fa1a7b9611a7b96ull };            // 1/1, 1/3, ..., 1/29 as the reference divides them
DSO_CONST ds_u64 dso_sc[8] = { 0x3ff0000000000000ull, 0xbfc5555555555555ull, 0x3f81111111111111ull, 0xbf2a01a01a01a01aull, 0x3ec71de3a556c734ull, 0xbe5ae64567f544e4ull, 0x3de6124613a86d09ull, 0xbd6ae7f3e733b81full };
DSO_CONST ds_u64 dso_cc[9] = { 0x3ff0000000000000ull, 0xbfe0000000000000ull, 0x3fa5555555555555ull, 0xbf56c16c16c16c17ull, 0x3efa01a01a01a01aull, 0xbe927e4fb7789f5cull, 0x3e21eed8eff8d898ull, 0xbda93974a8c07c9dull, 0x3d2ae7f3e733b81full };

// det_ldexp, mirrored literally (two-step scaling for large |k|)
DS_FN ds_u64 dso_ldexp(ds_u64 x, ds_i32 k) {
    if (k > 1023) {
        x = ds_mul(x, ((ds_u64) (1023 + 1023)) << 52); k -= 1023;
        if (k > 1023) { x = ds_mul(x, ((ds_u64) (1023 + 1023)) << 52); k -= 1023; if (k > 1023) k = 1023; }
    } else if (k < -1022) {
        x = ds_mul(x, ((ds_u64) (1023 - 1022)) << 52); k += 1022;
        if (k < -1022) { x = ds_mul(x, ((ds_u64) (1023 - 1022)) << 52); k += 1022; if (k < -1022) k = -1022; }
    }
    return ds_mul(x, ((ds_u64) (k + 1023)) << 52);
}

// e^r for |r| <= 0.36: Taylor to r^13
DS_FN ds_u64 dso_exp_small(ds_u64 r) {
    ds_u64 p = dso_expc[13];
    for (int i = 12; i >= 0; i--) p = ds_add(ds_mul(p, r), dso_expc[i]);
    return p;
}
DS_FN ds_u64 dso_exp_d(ds_u64 x) {
    const ds_u64 k = ds_floor(ds_add(ds_mul(x, DSO_INV_LN2), DSO_HALF));
    const ds_u64 r = ds_sub(ds_sub(x, ds_mul(k, DSO_LN2_HI)), ds_mul(k, DSO_LN2_LO));
    return dso_ldexp(dso_exp_small(r), (ds_i32) ds_to_i64_trunc(k));
}
DS_FN ds_u32 dso_expf_bits(ds_u32 b) {                 // det_expf on float bits
    if (((b >> 23) & 0xFF) == 0xFF) return (b & 0x7FFFFF) ? b : ((b >> 31) ? 0u : b);
    const float x = DSO_B2F(b);
    if (x > 88.75f) return 0x7F800000u;
    if (x < -104.0f) return 0u;
    return ds_to_f32bits(dso_exp_d(ds_from_f32bits(b)));
}
DS_FN ds_u64 dso_exp2_d(ds_u64 y) {
    const ds_u64 k = ds_floor(ds_add(y, DSO_HALF));
    const ds_u64 r = ds_sub(y, k);
    return dso_ldexp(dso_exp_small(ds_mul(r, DSO_LN2)), (ds_i32) ds_to_i64_trunc(k));
}
// log2(x), finite normal x > 0
DS_FN ds_u64 dso_log2_d(ds_u64 x) {
    ds_i32 e = (ds_i32) ((x >> 52) & 0x7FF) - 1023;
    ds_u64 m = (x & 0xFFFFFFFFFFFFFull) | (1023ull << 52);
    if (ds_lt(DSO_SQRT1_2, m) && !ds_eq(DSO_SQRT1_2, m)) { m = ds_mul(m, DSO_HALF); e++; }   // m > sqrt(2)
    const ds_u64 s  = ds_div(ds_sub(m, DSO_ONE), ds_add(m, DSO_ONE));
    const ds_u64 s2 = ds_mul(s, s);
    ds_u64 p = DSO_ZERO;
    for (int k = 29; k >= 1; k -= 2) p = ds_add(ds_mul(p, s2), dso_invk[(k - 1) / 2]);
    const ds_u64 ln_m = ds_mul(DSO_TWO, ds_mul(s, p));
    return ds_add(ds_from_i64(e), ds_mul(ln_m, DSO_INV_LN2));
}
// sin/cos after Cody-Waite reduction, Taylor
DS_FN void dso_sincos_d(ds_u64 x, DS_PTR(ds_u64) s, DS_PTR(ds_u64) c) {
    const ds_u64 n  = ds_floor(ds_add(ds_mul(x, DSO_TWO_OVER_PI), DSO_HALF));
    const ds_u64 r  = ds_sub(ds_sub(ds_sub(x, ds_mul(n, DSO_PIO2_1)), ds_mul(n, DSO_PIO2_2)), ds_mul(n, DSO_PIO2_3));
    const ds_u64 r2 = ds_mul(r, r);
    ds_u64 ps = dso_sc[7];
    for (int i = 6; i >= 0; i--) ps = ds_add(ds_mul(ps, r2), dso_sc[i]);
    ps = ds_mul(ps, r);
    ds_u64 pc = dso_cc[8];
    for (int i = 7; i >= 0; i--) pc = ds_add(ds_mul(pc, r2), dso_cc[i]);
    const ds_i64 q = ds_to_i64_trunc(n) & 3;
    switch (q) {
        case 0: *s = ps;          *c = pc;          break;
        case 1: *s = pc;          *c = ds_neg(ps);  break;
        case 2: *s = ds_neg(ps);  *c = ds_neg(pc);  break;
        default: *s = ds_neg(pc); *c = ps;          break;
    }
}
DS_FN void dso_sincosf_bits(ds_u32 theta, DS_PTR(ds_u32) s, DS_PTR(ds_u32) c) {
    ds_u64 sd, cd; dso_sincos_d(ds_from_f32bits(theta), &sd, &cd);
    *s = ds_to_f32bits(sd); *c = ds_to_f32bits(cd);
}
DS_FN ds_u64 dso_rope_freq(ds_i32 i, ds_i32 n_dims, ds_u32 freq_base) {
    const ds_u64 L = ds_mul(dso_log2_d(ds_from_f32bits(freq_base)), ds_div(ds_mul(DSO_M2, ds_from_i64(i)), ds_from_i64(n_dims)));
    return dso_exp2_d(L);
}
DS_FN void dso_rope_sincos(ds_u32 pos, ds_i32 i, ds_i32 n_dims, ds_u32 freq_base, ds_u32 freq_scale, DS_PTR(ds_u32) s, DS_PTR(ds_u32) c) {
    const ds_u64 theta = ds_mul(ds_mul(ds_from_f32bits(pos), dso_rope_freq(i, n_dims, freq_base)), ds_from_f32bits(freq_scale));
    ds_u64 sd, cd; dso_sincos_d(theta, &sd, &cd);
    *s = ds_to_f32bits(sd); *c = ds_to_f32bits(cd);
}
DS_FN void dso_rope_sincos_ff(ds_u32 pos, ds_i32 i, ds_i32 n_dims, ds_u32 freq_base, ds_u32 freq_scale, ds_u32 ff, DS_PTR(ds_u32) s, DS_PTR(ds_u32) c) {
    const ds_u64 theta = ds_mul(ds_div(ds_mul(ds_from_f32bits(pos), dso_rope_freq(i, n_dims, freq_base)), ds_from_f32bits(ff)), ds_from_f32bits(freq_scale));
    ds_u64 sd, cd; dso_sincos_d(theta, &sd, &cd);
    *s = ds_to_f32bits(sd); *c = ds_to_f32bits(cd);
}
DS_FN ds_u64 dso_tanh_d(ds_u64 y) {
    if (ds_lt(DSO_TWENTY, y)) return DSO_ONE;
    if (ds_lt(y, DSO_M_TWENTY)) return DSO_ONE | (1ull << 63);
    const ds_u64 u = dso_exp_d(ds_mul(DSO_TWO, y));
    return ds_div(ds_sub(u, DSO_ONE), ds_add(u, DSO_ONE));
}
DS_FN ds_u32 dso_tanhf_bits(ds_u32 b) {
    if (((b >> 23) & 0xFF) == 0xFF && (b & 0x7FFFFF)) return b;
    return ds_to_f32bits(dso_tanh_d(ds_from_f32bits(b)));
}
// float-domain formulas, the reference's operation order (float IEEE ops, no contraction)
#define DSO_GELU_COEF_A    0.044715f
#define DSO_SQRT_2_OVER_PI 0.79788456080286535587989211986876f
DS_FN float dso_geluf(float x) {
    const float inner = DSO_FMUL(DSO_SQRT_2_OVER_PI, DSO_FMUL(x, DSO_FADD(1.0f, DSO_FMUL(DSO_GELU_COEF_A, DSO_FMUL(x, x)))));
    return DSO_FMUL(DSO_FMUL(0.5f, x), DSO_FADD(1.0f, DSO_B2F(dso_tanhf_bits(DSO_F2B(inner)))));
}
DS_FN float dso_sigmoidf(float x) { return DSO_FDIV(1.0f, DSO_FADD(1.0f, DSO_B2F(dso_expf_bits(DSO_F2B(-x))))); }
DS_FN float dso_siluf(float x)    { return DSO_FMUL(x, dso_sigmoidf(x)); }

// ---- exact big accumulator (640-bit, radix 352): integer, shared with bp8_exact_soft's rule ----
#define DSO_BIG_LIMBS 20
#define DSO_BIG_RADIX 352
DS_FN void dso_big_zero(DS_PTR(ds_u32) acc) { for (int i = 0; i < DSO_BIG_LIMBS; i++) acc[i] = 0; }
// acc += v*v exactly from float bits; 0 for non-finite
DS_FN int dso_big_add_sq_bits(DS_PTR(ds_u32) acc, ds_u32 f) {
    if ((f & 0x7FFFFFFFu) == 0) return 1;
    const ds_i32 e = (f >> 23) & 0xFF; const ds_u64 mf = f & 0x7FFFFF;
    if (e == 0xFF) return 0;
    ds_u64 mant; ds_i32 e2;
    if (e == 0) { mant = mf; e2 = -149; } else { mant = mf | 0x800000ull; e2 = e - 127 - 23; }
    const ds_u64 P = mant * mant;
    const ds_i32 pos = 2 * e2 + DSO_BIG_RADIX;
    const ds_i32 w = pos >> 5, b = pos & 31;
    const ds_u64 lo = b ? (P << b) : P;
    const ds_u64 hi = b ? (P >> (64 - b)) : 0ull;
    ds_u32 parts[3]; parts[0] = (ds_u32) lo; parts[1] = (ds_u32) (lo >> 32); parts[2] = (ds_u32) hi;
    ds_u64 c = 0;
    for (int i = 0; i < 3; i++) { const ds_u64 t = (ds_u64) acc[w + i] + parts[i] + c; acc[w + i] = (ds_u32) t; c = t >> 32; }
    for (int i = w + 3; c && i < DSO_BIG_LIMBS; i++) { const ds_u64 t = (ds_u64) acc[i] + c; acc[i] = (ds_u32) t; c = t >> 32; }
    return 1;
}
// acc += v for a finite non-negative float (softmax numerators)
DS_FN void dso_big_add_f32_nonneg_bits(DS_PTR(ds_u32) acc, ds_u32 fb) {
    const ds_i32 e = (fb >> 23) & 0xFF, f = fb & 0x7FFFFF;
    if ((fb & 0x7FFFFFFFu) == 0 || e == 0xFF) return;
    ds_u64 mi; ds_i32 e2;
    if (e == 0) { mi = (ds_u64) f; e2 = -126 - 23; } else { mi = (ds_u64) (f | 0x800000); e2 = e - 127 - 23; }
    const ds_i32 pos = e2 + DSO_BIG_RADIX;
    const ds_i32 w = pos >> 5, b = pos & 31;
    const ds_u64 lo = b ? (mi << b) : mi;
    const ds_u64 hi = b ? (mi >> (64 - b)) : 0ull;
    ds_u32 parts[3]; parts[0] = (ds_u32) lo; parts[1] = (ds_u32) (lo >> 32); parts[2] = (ds_u32) hi;
    ds_u64 c = 0;
    for (int i = 0; i < 3; i++) { const ds_u64 t = (ds_u64) acc[w + i] + parts[i] + c; acc[w + i] = (ds_u32) t; c = t >> 32; }
    for (int i = w + 3; c && i < DSO_BIG_LIMBS; i++) { const ds_u64 t = (ds_u64) acc[i] + c; acc[i] = (ds_u32) t; c = t >> 32; }
}
DS_FN ds_i32 dso_big_top(const DS_PTR(ds_u32) acc) {
    for (int i = DSO_BIG_LIMBS - 1; i >= 0; i--) { if (acc[i]) { ds_i32 t = 31; while (!((acc[i] >> t) & 1u)) t--; return 32 * i + t; } }
    return -1;
}
DS_FN ds_u32 dso_big_bit(const DS_PTR(ds_u32) acc, ds_i32 j) { if (j < 0 || j >= 32 * DSO_BIG_LIMBS) return 0; return (acc[j >> 5] >> (j & 31)) & 1u; }
// correctly rounded double of S * 2^-RADIX
DS_FN ds_u64 dso_big_to_double(const DS_PTR(ds_u32) acc) {
    const ds_i32 t = dso_big_top(acc);
    if (t < 0) return DSO_ZERO;
    ds_u64 mant = 0;
    for (ds_i32 j = t; j > t - 53; j--) mant = (mant << 1) | dso_big_bit(acc, j);
    const ds_u32 guard = dso_big_bit(acc, t - 53);
    int sticky = 0;
    for (ds_i32 j = t - 54; j >= 0 && !sticky; j--) sticky |= dso_big_bit(acc, j);
    ds_i32 e = t - 52;
    if (guard && (sticky || (mant & 1u))) { mant++; if (mant == (1ull << 53)) { mant >>= 1; e++; } }
    return dso_ldexp(ds_from_i64((ds_i64) mant), e - DSO_BIG_RADIX);
}
// RMSNorm scale: mean = (float)(S/n); scale = 1/sqrtf(mean + eps)
DS_FN float dso_rms_scale(ds_u64 sumsq, ds_i32 n, float eps) {
    const float mean = DSO_B2F(ds_to_f32bits(ds_div(sumsq, ds_from_i64(n))));
    return DSO_FDIV(1.0f, DSO_FSQRT(DSO_FADD(mean, eps)));
}
DS_FN float dso_soft_max_inv(ds_u64 sum) { return DSO_FDIV(1.0f, DSO_B2F(ds_to_f32bits(sum))); }
#endif

#ifdef __METAL_VERSION__
constant ulong bp8_tab_sv[255] = {
    0xc170000000000000ul, 0xc130000000000000ul, 0xc110000000000000ul, 0xc0f0000000000000ul, 0xc0e0000000000000ul, 0xc0d0000000000000ul, 0xc0c0000000000000ul, 0xc0b0000000000000ul,
    0xc0a8000000000000ul, 0xc0a0000000000000ul, 0xc098000000000000ul, 0xc090000000000000ul, 0xc088000000000000ul, 0xc080000000000000ul, 0xc078000000000000ul, 0xc070000000000000ul,
    0xc06c000000000000ul, 0xc068000000000000ul, 0xc064000000000000ul, 0xc060000000000000ul, 0xc05c000000000000ul, 0xc058000000000000ul, 0xc054000000000000ul, 0xc050000000000000ul,
    0xc04c000000000000ul, 0xc048000000000000ul, 0xc044000000000000ul, 0xc040000000000000ul, 0xc03c000000000000ul, 0xc038000000000000ul, 0xc034000000000000ul, 0xc030000000000000ul,
    0xc02e000000000000ul, 0xc02c000000000000ul, 0xc02a000000000000ul, 0xc028000000000000ul, 0xc026000000000000ul, 0xc024000000000000ul, 0xc022000000000000ul, 0xc020000000000000ul,
    0xc01e000000000000ul, 0xc01c000000000000ul, 0xc01a000000000000ul, 0xc018000000000000ul, 0xc016000000000000ul, 0xc014000000000000ul, 0xc012000000000000ul, 0xc010000000000000ul,
    0xc00e000000000000ul, 0xc00c000000000000ul, 0xc00a000000000000ul, 0xc008000000000000ul, 0xc006000000000000ul, 0xc004000000000000ul, 0xc002000000000000ul, 0xc000000000000000ul,
    0xbffe000000000000ul, 0xbffc000000000000ul, 0xbffa000000000000ul, 0xbff8000000000000ul, 0xbff6000000000000ul, 0xbff4000000000000ul, 0xbff2000000000000ul, 0xbff0000000000000ul,
    0xbfee000000000000ul, 0xbfec000000000000ul, 0xbfea000000000000ul, 0xbfe8000000000000ul, 0xbfe6000000000000ul, 0xbfe4000000000000ul, 0xbfe2000000000000ul, 0xbfe0000000000000ul,
    0xbfde000000000000ul, 0xbfdc000000000000ul, 0xbfda000000000000ul, 0xbfd8000000000000ul, 0xbfd6000000000000ul, 0xbfd4000000000000ul, 0xbfd2000000000000ul, 0xbfd0000000000000ul,
    0xbfce000000000000ul, 0xbfcc000000000000ul, 0xbfca000000000000ul, 0xbfc8000000000000ul, 0xbfc6000000000000ul, 0xbfc4000000000000ul, 0xbfc2000000000000ul, 0xbfc0000000000000ul,
    0xbfbe000000000000ul, 0xbfbc000000000000ul, 0xbfba000000000000ul, 0xbfb8000000000000ul, 0xbfb6000000000000ul, 0xbfb4000000000000ul, 0xbfb2000000000000ul, 0xbfb0000000000000ul,
    0xbfac000000000000ul, 0xbfa8000000000000ul, 0xbfa4000000000000ul, 0xbfa0000000000000ul, 0xbf9c000000000000ul, 0xbf98000000000000ul, 0xbf94000000000000ul, 0xbf90000000000000ul,
    0xbf8c000000000000ul, 0xbf88000000000000ul, 0xbf84000000000000ul, 0xbf80000000000000ul, 0xbf7c000000000000ul, 0xbf78000000000000ul, 0xbf74000000000000ul, 0xbf70000000000000ul,
    0xbf68000000000000ul, 0xbf60000000000000ul, 0xbf58000000000000ul, 0xbf50000000000000ul, 0xbf48000000000000ul, 0xbf40000000000000ul, 0xbf38000000000000ul, 0xbf30000000000000ul,
    0xbf20000000000000ul, 0xbf10000000000000ul, 0xbf00000000000000ul, 0xbef0000000000000ul, 0xbed0000000000000ul, 0xbeb0000000000000ul, 0xbe70000000000000ul, 0x0000000000000000ul,
    0x3e70000000000000ul, 0x3eb0000000000000ul, 0x3ed0000000000000ul, 0x3ef0000000000000ul, 0x3f00000000000000ul, 0x3f10000000000000ul, 0x3f20000000000000ul, 0x3f30000000000000ul,
    0x3f38000000000000ul, 0x3f40000000000000ul, 0x3f48000000000000ul, 0x3f50000000000000ul, 0x3f58000000000000ul, 0x3f60000000000000ul, 0x3f68000000000000ul, 0x3f70000000000000ul,
    0x3f74000000000000ul, 0x3f78000000000000ul, 0x3f7c000000000000ul, 0x3f80000000000000ul, 0x3f84000000000000ul, 0x3f88000000000000ul, 0x3f8c000000000000ul, 0x3f90000000000000ul,
    0x3f94000000000000ul, 0x3f98000000000000ul, 0x3f9c000000000000ul, 0x3fa0000000000000ul, 0x3fa4000000000000ul, 0x3fa8000000000000ul, 0x3fac000000000000ul, 0x3fb0000000000000ul,
    0x3fb2000000000000ul, 0x3fb4000000000000ul, 0x3fb6000000000000ul, 0x3fb8000000000000ul, 0x3fba000000000000ul, 0x3fbc000000000000ul, 0x3fbe000000000000ul, 0x3fc0000000000000ul,
    0x3fc2000000000000ul, 0x3fc4000000000000ul, 0x3fc6000000000000ul, 0x3fc8000000000000ul, 0x3fca000000000000ul, 0x3fcc000000000000ul, 0x3fce000000000000ul, 0x3fd0000000000000ul,
    0x3fd2000000000000ul, 0x3fd4000000000000ul, 0x3fd6000000000000ul, 0x3fd8000000000000ul, 0x3fda000000000000ul, 0x3fdc000000000000ul, 0x3fde000000000000ul, 0x3fe0000000000000ul,
    0x3fe2000000000000ul, 0x3fe4000000000000ul, 0x3fe6000000000000ul, 0x3fe8000000000000ul, 0x3fea000000000000ul, 0x3fec000000000000ul, 0x3fee000000000000ul, 0x3ff0000000000000ul,
    0x3ff2000000000000ul, 0x3ff4000000000000ul, 0x3ff6000000000000ul, 0x3ff8000000000000ul, 0x3ffa000000000000ul, 0x3ffc000000000000ul, 0x3ffe000000000000ul, 0x4000000000000000ul,
    0x4002000000000000ul, 0x4004000000000000ul, 0x4006000000000000ul, 0x4008000000000000ul, 0x400a000000000000ul, 0x400c000000000000ul, 0x400e000000000000ul, 0x4010000000000000ul,
    0x4012000000000000ul, 0x4014000000000000ul, 0x4016000000000000ul, 0x4018000000000000ul, 0x401a000000000000ul, 0x401c000000000000ul, 0x401e000000000000ul, 0x4020000000000000ul,
    0x4022000000000000ul, 0x4024000000000000ul, 0x4026000000000000ul, 0x4028000000000000ul, 0x402a000000000000ul, 0x402c000000000000ul, 0x402e000000000000ul, 0x4030000000000000ul,
    0x4034000000000000ul, 0x4038000000000000ul, 0x403c000000000000ul, 0x4040000000000000ul, 0x4044000000000000ul, 0x4048000000000000ul, 0x404c000000000000ul, 0x4050000000000000ul,
    0x4054000000000000ul, 0x4058000000000000ul, 0x405c000000000000ul, 0x4060000000000000ul, 0x4064000000000000ul, 0x4068000000000000ul, 0x406c000000000000ul, 0x4070000000000000ul,
    0x4078000000000000ul, 0x4080000000000000ul, 0x4088000000000000ul, 0x4090000000000000ul, 0x4098000000000000ul, 0x40a0000000000000ul, 0x40a8000000000000ul, 0x40b0000000000000ul,
    0x40c0000000000000ul, 0x40d0000000000000ul, 0x40e0000000000000ul, 0x40f0000000000000ul, 0x4110000000000000ul, 0x4130000000000000ul, 0x4170000000000000ul
};
constant uint bp8_tab_sc[255] = {
    129, 130, 131, 132, 133, 134, 135, 136,
    137, 138, 139, 140, 141, 142, 143, 144,
    145, 146, 147, 148, 149, 150, 151, 152,
    153, 154, 155, 156, 157, 158, 159, 160,
    161, 162, 163, 164, 165, 166, 167, 168,
    169, 170, 171, 172, 173, 174, 175, 176,
    177, 178, 179, 180, 181, 182, 183, 184,
    185, 186, 187, 188, 189, 190, 191, 192,
    193, 194, 195, 196, 197, 198, 199, 200,
    201, 202, 203, 204, 205, 206, 207, 208,
    209, 210, 211, 212, 213, 214, 215, 216,
    217, 218, 219, 220, 221, 222, 223, 224,
    225, 226, 227, 228, 229, 230, 231, 232,
    233, 234, 235, 236, 237, 238, 239, 240,
    241, 242, 243, 244, 245, 246, 247, 248,
    249, 250, 251, 252, 253, 254, 255, 0,
    1, 2, 3, 4, 5, 6, 7, 8,
    9, 10, 11, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23, 24,
    25, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48,
    49, 50, 51, 52, 53, 54, 55, 56,
    57, 58, 59, 60, 61, 62, 63, 64,
    65, 66, 67, 68, 69, 70, 71, 72,
    73, 74, 75, 76, 77, 78, 79, 80,
    81, 82, 83, 84, 85, 86, 87, 88,
    89, 90, 91, 92, 93, 94, 95, 96,
    97, 98, 99, 100, 101, 102, 103, 104,
    105, 106, 107, 108, 109, 110, 111, 112,
    113, 114, 115, 116, 117, 118, 119, 120,
    121, 122, 123, 124, 125, 126, 127
};
constant int bp8_tab_M[256] = {
    0, 1, 1, 1, 1, 1, 1, 1,
    2, 3, 2, 3, 2, 3, 2, 3,
    4, 5, 6, 7, 4, 5, 6, 7,
    4, 5, 6, 7, 4, 5, 6, 7,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    8, 9, 10, 11, 12, 13, 14, 15,
    4, 5, 6, 7, 4, 5, 6, 7,
    4, 5, 6, 7, 4, 5, 6, 7,
    2, 3, 2, 3, 2, 3, 2, 3,
    1, 1, 1, 1, 1, 1, 1, 1,
    0, -1, -1, -1, -1, -1, -1, -1,
    -1, -3, -2, -3, -2, -3, -2, -3,
    -2, -7, -6, -5, -4, -7, -6, -5,
    -4, -7, -6, -5, -4, -7, -6, -5,
    -4, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -15, -14, -13, -12, -11, -10, -9,
    -8, -7, -6, -5, -4, -7, -6, -5,
    -4, -7, -6, -5, -4, -7, -6, -5,
    -4, -3, -2, -3, -2, -3, -2, -3,
    -2, -1, -1, -1, -1, -1, -1, -1
};
constant int bp8_tab_E[256] = {
    0, -24, -20, -18, -16, -15, -14, -13,
    -13, -13, -12, -12, -11, -11, -10, -10,
    -10, -10, -10, -10, -9, -9, -9, -9,
    -8, -8, -8, -8, -7, -7, -7, -7,
    -7, -7, -7, -7, -7, -7, -7, -7,
    -6, -6, -6, -6, -6, -6, -6, -6,
    -5, -5, -5, -5, -5, -5, -5, -5,
    -4, -4, -4, -4, -4, -4, -4, -4,
    -3, -3, -3, -3, -3, -3, -3, -3,
    -2, -2, -2, -2, -2, -2, -2, -2,
    -1, -1, -1, -1, -1, -1, -1, -1,
    0, 0, 0, 0, 0, 0, 0, 0,
    2, 2, 2, 2, 3, 3, 3, 3,
    4, 4, 4, 4, 5, 5, 5, 5,
    7, 7, 8, 8, 9, 9, 10, 10,
    12, 13, 14, 15, 16, 18, 20, 24,
    0, 24, 20, 18, 16, 15, 14, 13,
    12, 10, 10, 9, 9, 8, 8, 7,
    7, 5, 5, 5, 5, 4, 4, 4,
    4, 3, 3, 3, 3, 2, 2, 2,
    2, 0, 0, 0, 0, 0, 0, 0,
    0, -1, -1, -1, -1, -1, -1, -1,
    -1, -2, -2, -2, -2, -2, -2, -2,
    -2, -3, -3, -3, -3, -3, -3, -3,
    -3, -4, -4, -4, -4, -4, -4, -4,
    -4, -5, -5, -5, -5, -5, -5, -5,
    -5, -6, -6, -6, -6, -6, -6, -6,
    -6, -7, -7, -7, -7, -7, -7, -7,
    -7, -7, -7, -7, -7, -8, -8, -8,
    -8, -9, -9, -9, -9, -10, -10, -10,
    -10, -10, -10, -11, -11, -12, -12, -13,
    -13, -13, -14, -15, -16, -18, -20, -24
};

#define BP8_NSG 4   // simdgroups (output rows) per threadgroup

// one thread per 32-element block of src1 (f32) -> block_bposit8, blocks laid out [i3][i2][i1][ib]
kernel void kernel_quantize_bposit8_f32(
        constant ggml_metal_kargs_bp8_quant & args,
        device const float * x,
        device block_bposit8 * y,
        uint tid [[thread_position_in_grid]]) {
    const long b = (long) tid;
    if (b >= args.nblk_total) return;
    const long ib = b % args.nblk_row;
    long r = b / args.nblk_row;
    const long i1 = r % args.ne1; r /= args.ne1;
    const long i2 = r % args.ne2;
    const long i3 = r / args.ne2;
    device const float * xr = x + i3 * args.s3 + i2 * args.s2 + i1 * args.s1 + ib * BP8_QK;
    uint xb[BP8_QK];
    for (int j = 0; j < BP8_QK; j++) xb[j] = as_type<uint>(xr[j]);
    int se; uint qs[BP8_QK];
    bp8_quantize_block_soft(xb, &se, qs, bp8_tab_sv, bp8_tab_sc);
    device block_bposit8 * yb = y + b;
    yb->scale_exp = (char) se;
    for (int j = 0; j < BP8_QK; j++) yb->qs[j] = (uchar) qs[j];
}

// exact dot: one simdgroup per output element; lanes stride the blocks; 8 int64 limbs per lane
// summed through threadgroup memory, carry-normalised once, read out through the software double
kernel void kernel_mul_mv_bposit8_exact(
        constant ggml_metal_kargs_bp8_mv & args,
        device const block_bposit8 * x,
        device const block_bposit8 * y,
        device float * dst,
        threadgroup long * red [[threadgroup(0)]],
        uint3  tgpig [[threadgroup_position_in_grid]],
        ushort tiisg [[thread_index_in_simdgroup]],
        ushort sgitg [[simdgroup_index_in_threadgroup]]) {
    const int  lane = tiisg;
    const long row  = (long) tgpig.x * BP8_NSG + sgitg;
    if (row >= args.ne01) return;                              // the whole simdgroup leaves together
    const long i1 = tgpig.y;
    const long i2 = tgpig.z % args.ne12, i3 = tgpig.z / args.ne12;
    device const block_bposit8 * xr = x + (i3 / args.r3) * args.s03 + (i2 / args.r2) * args.s02 + row * args.s01;
    device const block_bposit8 * yr = y + i3 * args.s13 + i2 * args.s12 + i1 * args.s11;
    long a[8];
    for (int w = 0; w < 8; w++) a[w] = 0;
    for (int ib = lane; ib < args.nblk; ib += 32) {
        const int se = (int) xr[ib].scale_exp + (int) yr[ib].scale_exp + BP8_QFRAC;
        for (int j = 0; j < BP8_QK; j++) {
            const uint cx = xr[ib].qs[j], cy = yr[ib].qs[j];
            const int P = bp8_tab_M[cx] * bp8_tab_M[cy];
            if (P == 0) continue;
            bp8_lane_add(a, (long) P, bp8_tab_E[cx] + bp8_tab_E[cy] + se);
        }
    }
    threadgroup long * r = red + ((int) sgitg * 32) * 8;
    for (int w = 0; w < 8; w++) r[lane * 8 + w] = a[w];
    metal::simdgroup_barrier(metal::mem_flags::mem_threadgroup);
    if (lane != 0) return;
    long s[8];
    for (int w = 0; w < 8; w++) { long t = 0; for (int l = 0; l < 32; l++) t += r[l * 8 + w]; s[w] = t; }
    uint q[8];
    bp8_limbs_to_q256(s, q);
    const uint out = bp8_q256_to_f32bits(q);
    dst[i3 * args.sd3 + i2 * args.sd2 + i1 * args.sd1 + row] = as_type<float>(out);
}

// ---------------------------------------------------------------------------------------
// exact f16 matmul (attention KQ / KQV with -fa off): src1 f32 -> f16 (IEEE RN-even, integer
// form == ggml_cpu_fp32_to_fp16), then det_dot_f16 per output: products M*M at 2^(Ex+Ey) into
// the same lazily-carried 256-bit quire and the same limb-to-double readout as the CPU path
// ---------------------------------------------------------------------------------------
static inline ushort dso_f32_to_f16bits(uint w) {
    const uint sign = (w >> 16) & 0x8000u;
    const int  e    = (int) ((w >> 23) & 0xFFu);
    const uint m    = w & 0x7FFFFFu;
    if (e == 0xFF) return (ushort) (sign | 0x7C00u | (m ? (0x200u | (m >> 13)) : 0u));   // inf / quiet NaN
    const int E = e - 112;                                       // f16 biased exponent
    uint mant; int shift;
    if (E > 0) { mant = m | 0x800000u; shift = 13; }
    else       { if (e == 0) return (ushort) sign; mant = m | 0x800000u; shift = 13 + (1 - E); if (shift > 24) return (ushort) sign; }
    uint q = mant >> shift;
    const uint rem = mant & ((1u << shift) - 1u), half_ = 1u << (shift - 1);
    if (rem > half_ || (rem == half_ && (q & 1u))) q++;
    uint out = (E > 0) ? (((uint) E << 10) + q - (1u << 10)) : q;   // q carries into the exponent when it overflows
    if (out >= 0x7C00u) out = 0x7C00u;                            // overflow -> inf
    return (ushort) (sign | out);
}
// IEEE binary16 -> M * 2^E (M = 0 for inf/nan), == det_f16_to_ME
static inline void dso_f16_to_ME(uint h, thread int * M, thread int * E) {
    const int s = (h >> 15) & 1, e = (h >> 10) & 0x1F, f = h & 0x3FF;
    int m;
    if (e == 0)       { m = f;        *E = -24; }
    else if (e == 31) { m = 0;        *E = 0;   }
    else              { m = 1024 + f; *E = e - 25; }
    *M = s ? -m : m;
}
// one thread per element of src1 (f32, strided rows) -> contiguous f16 [i3][i2][i1][k]
kernel void kernel_cvt_f32_f16_det(
        constant ggml_metal_kargs_bp8_quant & args,   // nblk_row = ne10, nblk_total = elements
        device const float * x,
        device ushort * y,
        uint tid [[thread_position_in_grid]]) {
    const long t = (long) tid;
    if (t >= args.nblk_total) return;
    const long k = t % args.nblk_row;
    long r = t / args.nblk_row;
    const long i1 = r % args.ne1; r /= args.ne1;
    const long i2 = r % args.ne2;
    const long i3 = r / args.ne2;
    y[t] = dso_f32_to_f16bits(as_type<uint>(x[i3 * args.s3 + i2 * args.s2 + i1 * args.s1 + k]));
}
// one simdgroup per output element; lanes stride k; strides in elements (src0 nb00 == 2)
kernel void kernel_mul_mv_f16_exact(
        constant ggml_metal_kargs_bp8_mv & args,      // nblk = ne00
        device const ushort * x,
        device const ushort * y,
        device float * dst,
        threadgroup long * red [[threadgroup(0)]],
        uint3  tgpig [[threadgroup_position_in_grid]],
        ushort tiisg [[thread_index_in_simdgroup]],
        ushort sgitg [[simdgroup_index_in_threadgroup]]) {
    const int  lane = tiisg;
    const long row  = (long) tgpig.x * BP8_NSG + sgitg;
    if (row >= args.ne01) return;
    const long i1 = tgpig.y;
    const long i2 = tgpig.z % args.ne12, i3 = tgpig.z / args.ne12;
    device const ushort * xr = x + (i3 / args.r3) * args.s03 + (i2 / args.r2) * args.s02 + row * args.s01;
    device const ushort * yr = y + i3 * args.s13 + i2 * args.s12 + i1 * args.s11;
    long a[8];
    for (int w = 0; w < 8; w++) a[w] = 0;
    for (int k = lane; k < args.nblk; k += 32) {
        int Mx, Ex, My, Ey;
        dso_f16_to_ME(xr[k], &Mx, &Ex);
        dso_f16_to_ME(yr[k], &My, &Ey);
        const int P = Mx * My;
        if (P == 0) continue;
        bp8_lane_add(a, (long) P, Ex + Ey + BP8_QFRAC);
    }
    threadgroup long * r = red + ((int) sgitg * 32) * 8;
    for (int w = 0; w < 8; w++) r[lane * 8 + w] = a[w];
    metal::simdgroup_barrier(metal::mem_flags::mem_threadgroup);
    if (lane != 0) return;
    long s[8];
    for (int w = 0; w < 8; w++) { long t = 0; for (int l = 0; l < 32; l++) t += r[l * 8 + w]; s[w] = t; }
    uint q[8];
    bp8_limbs_to_q256(s, q);
    const uint out = bp8_q256_to_f32bits(q);
    dst[i3 * args.sd3 + i2 * args.sd2 + i1 * args.sd1 + row] = as_type<float>(out);
}

// ---------------------------------------------------------------------------------------
// exact-profile elementwise / row ops on the software double (contract off is set by the
// #pragma in ggml-metal.metal under ANOMLY_METAL_EXACT)
// ---------------------------------------------------------------------------------------
#define DSO_NLIMB 20

// 64-bit simdgroup sum of one value via two 32-bit shuffles
static inline ulong dso_simd_sum_u64(ulong v, ushort tiisg) {
    for (ushort off = 16; off > 0; off >>= 1) {
        const uint lo = simd_shuffle_xor((uint) v, off);
        const uint hi = simd_shuffle_xor((uint) (v >> 32), off);
        v += ((ulong) hi << 32) | lo;
    }
    return v;
}
// reduce a per-thread 20-limb accumulator over the threadgroup into `out` (thread 0 only,
// carry-normalised 32-bit limbs). red: threadgroup ulong[nsg*20]. All threads must call.
static inline void dso_big_reduce_tg(thread const uint * acc, threadgroup ulong * red, thread uint * out,
                                     ushort tiisg, ushort sgitg, ushort nsg, ushort tpitg) {
    for (int i = 0; i < DSO_NLIMB; i++) {
        const ulong v = dso_simd_sum_u64((ulong) acc[i], tiisg);
        if (tiisg == 0) red[sgitg * DSO_NLIMB + i] = v;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (tpitg == 0) {
        ulong carry = 0;
        for (int i = 0; i < DSO_NLIMB; i++) {
            ulong t = carry;
            for (ushort g = 0; g < nsg; g++) t += red[g * DSO_NLIMB + i];   // < nsg * 2^37 + carry: no overflow
            out[i] = (uint) t; carry = t >> 32;
        }
    }
}

// same, but the reduced limbs are broadcast: EVERY thread leaves with `out` filled and the
// tail of the kernel stays uniform (a heavy thread-0-only block followed by a barrier and a
// threadgroup broadcast miscompiled on the M4 Pro: the other threads never ran the tail)
static inline void dso_big_reduce_tg_bcast(thread const uint * acc, threadgroup ulong * red, thread uint * out,
                                           ushort tiisg, ushort sgitg, ushort nsg, ushort tpitg) {
    dso_big_reduce_tg(acc, red, out, tiisg, sgitg, nsg, tpitg);
    if (tpitg == 0) { for (int i = 0; i < DSO_NLIMB; i++) red[i] = out[i]; }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (int i = 0; i < DSO_NLIMB; i++) out[i] = (uint) red[i];
}

// RMSNorm: F == 1 plain, F == 2 fused mul, F == 3 fused mul + add — the reference's rounding order
template <short F>
kernel void kernel_rms_norm_exact_impl(
        constant ggml_metal_kargs_norm & args,
        device const char * src0,
        device const char * src1_0,
        device const char * src1_1,
        device       char * dst,
        threadgroup ulong * red [[threadgroup(0)]],
        uint3   tgpig[[threadgroup_position_in_grid]],
        ushort3 tpitg[[thread_position_in_threadgroup]],
        ushort  sgitg[[simdgroup_index_in_threadgroup]],
        ushort  tiisg[[thread_index_in_simdgroup]],
        ushort3   ntg[[threads_per_threadgroup]]) {
    const int i01 = tgpig.x, i02 = tgpig.y, i03 = tgpig.z;
    device const float * x  = (device const float *) (src0 + i03*args.nbf3[0] + i02*args.nbf2[0] + i01*args.nbf1[0]);
    device const float * f0 = (device const float *) (src1_0 + (i03%args.nef3[1])*args.nbf3[1] + (i02%args.nef2[1])*args.nbf2[1] + (i01%args.nef1[1])*args.nbf1[1]);
    device const float * f1 = (device const float *) (src1_1 + (i03%args.nef3[2])*args.nbf3[2] + (i02%args.nef2[2])*args.nbf2[2] + (i01%args.nef1[2])*args.nbf1[2]);
    const ushort nsg = (ntg.x + 31) / 32;           // the op rounds nth up to whole simdgroups
    uint acc[DSO_NLIMB]; dso_big_zero(acc);
    int finite = 1;
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += ntg.x) finite &= dso_big_add_sq_bits(acc, as_type<uint>(x[i00]));
    finite = simd_min(finite);
    threadgroup float * bc = (threadgroup float *) (red + 32 * DSO_NLIMB);   // [0] scale, [2 + sg] finite flags
    if (tiisg == 0) bc[2 + sgitg] = (float) finite;
    uint S[DSO_NLIMB];
    dso_big_reduce_tg(acc, red, S, tiisg, sgitg, nsg, tpitg.x);            // contains the barrier
    if (tpitg.x == 0) {
        int all_finite = 1;
        for (ushort g = 0; g < nsg; g++) all_finite &= (bc[2 + g] != 0.0f);
        const ulong sumsq = all_finite ? dso_big_to_double(S) : DSO_INF;
        bc[0] = dso_rms_scale(sumsq, args.ne00, args.eps);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    const float scale = bc[0];
    device float * y = (device float *) (dst + i03*args.nb3 + i02*args.nb2 + i01*args.nb1);
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += ntg.x) {
        if (F == 1) y[i00] = DSO_FMUL(x[i00], scale);
        if (F == 2) y[i00] = DSO_FMUL(DSO_FMUL(x[i00], scale), f0[i00]);
        if (F == 3) y[i00] = DSO_FADD(DSO_FMUL(DSO_FMUL(x[i00], scale), f0[i00]), f1[i00]);
    }
}
typedef decltype(kernel_rms_norm_exact_impl<1>) kernel_rms_norm_exact_t;
template [[host_name("kernel_rms_norm_f32_exact")]]         kernel kernel_rms_norm_exact_t kernel_rms_norm_exact_impl<1>;
template [[host_name("kernel_rms_norm_mul_f32_exact")]]     kernel kernel_rms_norm_exact_t kernel_rms_norm_exact_impl<2>;
template [[host_name("kernel_rms_norm_mul_add_f32_exact")]] kernel kernel_rms_norm_exact_t kernel_rms_norm_exact_impl<3>;

// mask element -> float bits (f16 masks converted in integers: no FTZ on subnormal halves)
static inline uint dso_mask_f32bits(half m)  { return dso_f16_to_f32bits((uint) as_type<ushort>(m)); }
static inline uint dso_mask_f32bits(float m) { return as_type<uint>(m); }

// softmax (no ALiBi: max_bias == 0 is enforced by supports_op): wp = x*scale + slope*mask,
// max, y = expf(wp - max), EXACT sum (+ sink), y *= 1/(float)sum
template<typename TM>
kernel void kernel_soft_max_exact(
        constant ggml_metal_kargs_soft_max & args,
        device const  char * src0,
        device const  char * src1,
        device const  char * src2,
        device        char * dst,
        threadgroup  ulong * red [[threadgroup(0)]],
        uint3 tgpig[[threadgroup_position_in_grid]],
        uint3 tpitg[[thread_position_in_threadgroup]],
        uint  sgitg[[simdgroup_index_in_threadgroup]],
        uint  tiisg[[thread_index_in_simdgroup]],
        uint3  tptg[[threads_per_threadgroup]]) {
    const int32_t i03 = tgpig.z, i02 = tgpig.y, i01 = tgpig.x;
    const int32_t i13 = i03%args.ne13, i12 = i02%args.ne12, i11 = i01;
    device const float * psrc0 =                (device const float *) (src0 + i01*args.nb01 + i02*args.nb02 + i03*args.nb03);
    device const    TM * pmask = src1 != src0 ? (device const TM *   ) (src1 + i11*args.nb11 + i12*args.nb12 + i13*args.nb13) : nullptr;
    device const float * psrc2 = src2 != src0 ? (device const float *) (src2)                                                 : nullptr;
    device       float * pdst  =                (device       float *) (dst  + i01*args.nb1  + i02*args.nb2  + i03*args.nb3);
    threadgroup uint * fb = (threadgroup uint *) (red + 32 * DSO_NLIMB);   // [0..31] per-simdgroup max (float bits)
    const ushort nsg = (tptg.x + 31) / 32;
    const uint scale_b = as_type<uint>(args.scale);
    // all float ops on the software binary32 (no FTZ), MAX on the bit order; slope == 1: slope*mask == mask
    // pass 1: max of wp (the reference: wp = x*scale, then wp += slope*mask)
    uint lmax = 0xFF800000u;   // -inf
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += tptg.x) {
        uint wp = dso_fmul_bits(as_type<uint>(psrc0[i00]), scale_b);
        if (pmask) wp = dso_fadd_bits(wp, dso_mask_f32bits(pmask[i00]));
        lmax = dso_fmax_bits(lmax, wp);
    }
    uint max_b = dso_funkey(simd_max(dso_fkey(lmax)));
    if (tiisg == 0) fb[sgitg] = max_b;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    max_b = 0xFF800000u;
    for (ushort g = 0; g < nsg; g++) max_b = dso_fmax_bits(max_b, fb[g]);
    if (psrc2) max_b = dso_fmax_bits(max_b, as_type<uint>(psrc2[i02]));
    // pass 2: y = expf(wp - max), exact sum
    uint acc[DSO_NLIMB]; dso_big_zero(acc);
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += tptg.x) {
        uint wp = dso_fmul_bits(as_type<uint>(psrc0[i00]), scale_b);
        if (pmask) wp = dso_fadd_bits(wp, dso_mask_f32bits(pmask[i00]));
        const uint yb = dso_expf_bits(dso_fsub_bits(wp, max_b));
        pdst[i00] = as_type<float>(yb);
        dso_big_add_f32_nonneg_bits(acc, yb);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);   // fb reads done before red is reused
    uint S[DSO_NLIMB];
    dso_big_reduce_tg_bcast(acc, red, S, tiisg, sgitg, nsg, tpitg.x);
    // uniform tail: every thread derives the same inv from the same limbs (psrc2 is uniform)
    if (psrc2) { const uint se = dso_expf_bits(dso_fsub_bits(as_type<uint>(psrc2[i02]), max_b)); if (!dso_f_is_zero(se)) dso_big_add_f32_nonneg_bits(S, se); }
    const uint inv_b = as_type<uint>(dso_soft_max_inv(dso_big_to_double(S)));
    for (int i00 = tpitg.x; i00 < args.ne00; i00 += tptg.x) pdst[i00] = as_type<float>(dso_fmul_bits(as_type<uint>(pdst[i00]), inv_b));
}
typedef decltype(kernel_soft_max_exact<float>) kernel_soft_max_exact_t;
template [[host_name("kernel_soft_max_f32_exact")]] kernel kernel_soft_max_exact_t kernel_soft_max_exact<float>;
template [[host_name("kernel_soft_max_f16_exact")]] kernel kernel_soft_max_exact_t kernel_soft_max_exact<half>;

// RoPE (ext_factor == 0, f32, forward): cos/sin from the exact table rule, mscale = attn_factor
static inline void dso_rope_pair(constant ggml_metal_kargs_rope & args, device const char * src2, float theta_base, int ic,
                                 thread float * cos_theta, thread float * sin_theta) {
    uint s, c;
    if (args.src2) dso_rope_sincos_ff(as_type<uint>(theta_base), ic, args.n_dims, as_type<uint>(args.freq_base), as_type<uint>(args.freq_scale), as_type<uint>(((device const float *) src2)[ic]), &s, &c);
    else           dso_rope_sincos(as_type<uint>(theta_base), ic, args.n_dims, as_type<uint>(args.freq_base), as_type<uint>(args.freq_scale), &s, &c);
    *cos_theta = DSO_FMUL(as_type<float>(c), args.attn_factor);
    *sin_theta = DSO_FMUL(as_type<float>(s), args.attn_factor);
}
kernel void kernel_rope_norm_f32_exact(
        constant ggml_metal_kargs_rope & args,
        device const char * src0, device const char * src1, device const char * src2, device char * dst,
        ushort tiitg[[thread_index_in_threadgroup]], ushort3 tptg [[threads_per_threadgroup]], uint3 tgpig[[threadgroup_position_in_grid]]) {
    const int i3 = tgpig[2], i2 = tgpig[1], i1 = tgpig[0];
    device const int32_t * pos = (device const int32_t *) src1;
    const float theta_base = (float) pos[i2];
    for (int i0 = 2*tiitg; i0 < args.ne0; i0 += 2*tptg.x) {
        device const float * const src = (device float *)(src0 + i3*args.nb03 + i2*args.nb02 + i1*args.nb01 + i0*args.nb00);
        device       float * dst_data  = (device float *)( dst + i3*args.nb3  + i2*args.nb2  + i1*args.nb1  + i0*args.nb0);
        if (i0 < args.n_dims) {
            float c, s; dso_rope_pair(args, src2, theta_base, i0/2, &c, &s);
            const float x0 = src[0], x1 = src[1];
            dst_data[0] = DSO_FSUB(DSO_FMUL(x0, c), DSO_FMUL(x1, s));
            dst_data[1] = DSO_FADD(DSO_FMUL(x0, s), DSO_FMUL(x1, c));
        } else { dst_data[0] = src[0]; dst_data[1] = src[1]; }
    }
}
kernel void kernel_rope_neox_f32_exact(
        constant ggml_metal_kargs_rope & args,
        device const char * src0, device const char * src1, device const char * src2, device char * dst,
        ushort tiitg[[thread_index_in_threadgroup]], ushort3 tptg [[threads_per_threadgroup]], uint3 tgpig[[threadgroup_position_in_grid]]) {
    const int i3 = tgpig[2], i2 = tgpig[1], i1 = tgpig[0];
    device const int32_t * pos = (device const int32_t *) src1;
    const float theta_base = (float) pos[i2];
    for (int i0 = 2*tiitg; i0 < args.ne0; i0 += 2*tptg.x) {
        if (i0 < args.n_dims) {
            const int ic = i0/2;
            float c, s; dso_rope_pair(args, src2, theta_base, ic, &c, &s);
            device const float * const src = (device float *)(src0 + i3*args.nb03 + i2*args.nb02 + i1*args.nb01 + ic*args.nb00);
            device       float * dst_data  = (device float *)( dst + i3*args.nb3  + i2*args.nb2  + i1*args.nb1  + ic*args.nb0);
            const float x0 = src[0], x1 = src[args.n_dims/2];
            dst_data[0]             = DSO_FSUB(DSO_FMUL(x0, c), DSO_FMUL(x1, s));
            dst_data[args.n_dims/2] = DSO_FADD(DSO_FMUL(x0, s), DSO_FMUL(x1, c));
        } else {
            device const float * const src = (device float *)(src0 + i3*args.nb03 + i2*args.nb02 + i1*args.nb01 + i0*args.nb00);
            device       float * dst_data  = (device float *)( dst + i3*args.nb3  + i2*args.nb2  + i1*args.nb1  + i0*args.nb0);
            dst_data[0] = src[0]; dst_data[1] = src[1];
        }
    }
}

// SwiGLU: silu(x0) * x1 with the reference's silu
kernel void kernel_swiglu_f32_exact(
        constant ggml_metal_kargs_glu & args,
        device const char * src0, device const char * src1, device char * dst,
        uint tgpig[[threadgroup_position_in_grid]], uint tpitg[[thread_position_in_threadgroup]], uint ntg[[threads_per_threadgroup]]) {
    device const float * src0_row = (device const float *) ((device const char *) src0 + tgpig*args.nb01) + args.i00;
    device const float * src1_row = (device const float *) ((device const char *) src1 + tgpig*args.nb11) + args.i10;
    device       float * dst_row  = (device       float *) ((device       char *) dst  + tgpig*args.nb1);
    for (int i0 = tpitg; i0 < args.ne0; i0 += ntg) dst_row[i0] = DSO_FMUL(dso_siluf(src0_row[i0]), src1_row[i0]);
}

// vector overloads for the unary kernel's float4 instantiation
static inline float  dso_silu_v(float  x) { return dso_siluf(x); }
static inline float4 dso_silu_v(float4 x) { return float4(dso_siluf(x.x), dso_siluf(x.y), dso_siluf(x.z), dso_siluf(x.w)); }
static inline float  dso_gelu_v(float  x) { return dso_geluf(x); }
static inline float4 dso_gelu_v(float4 x) { return float4(dso_geluf(x.x), dso_geluf(x.y), dso_geluf(x.z), dso_geluf(x.w)); }
#endif // __METAL_VERSION__
#endif // GGML_METAL_BPOSIT8_H
