#!/usr/bin/env python3
# Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
"""Emit det_soft_ops.h: ggml-det.h's double-based routines (exp, exp2, log2, sin/cos, rope, tanh,
gelu, silu, sigmoid, RMS scale, softmax) rewritten on det_soft.h's software binary64 (bits), so
they compile unchanged as C and as Metal Shading Language. Constants are emitted as exact bit
patterns of the reference's double literals."""
import struct
def d(x): return "0x%016xull" % struct.unpack('<Q', struct.pack('<d', x))[0]
def arr(name, vals): return "static const ds_u64 %s[%d] = { %s };" % (name, len(vals), ", ".join(d(v) for v in vals))
expc = [1.0, 1.0, 5.00000000000000000000e-01, 1.66666666666666657415e-01, 4.16666666666666643537e-02,
        8.33333333333333321769e-03, 1.38888888888888894189e-03, 1.98412698412698412526e-04,
        2.48015873015873015658e-05, 2.75573192239858925110e-06, 2.75573192239858883130e-07,
        2.50521083854417202234e-08, 2.08767569878681002718e-09, 1.60590438368216133364e-10]
sc = [1.0, -1.66666666666666657415e-01, 8.33333333333333321769e-03, -1.98412698412698412526e-04,
      2.75573192239858925110e-06, -2.50521083854417202234e-08, 1.60590438368216133364e-10, -7.64716373181981647590e-13]
cc = [1.0, -5.00000000000000000000e-01, 4.16666666666666643537e-02, -1.38888888888888894189e-03,
      2.48015873015873015658e-05, -2.75573192239858883130e-07, 2.08767569878681002718e-09,
      -1.14707455977297245139e-11, 4.77947733238738529744e-14]
inv_k = [1.0 / k for k in range(1, 30, 2)]   # 1/1, 1/3, ..., 1/29 as the reference computes DET_DDIV(1.0, k)
out = r'''// Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
// det_soft_ops.h — GENERATED by gen_det_soft_ops.py. ggml-det.h's exact-profile routines that use
// double, rewritten on det_soft.h (software binary64 on integers) so they run where there is no
// double (Metal). Operation order is the reference's, so results are bit-identical.
// Constants are the exact bit patterns of the reference's literals.
#ifndef DET_SOFT_OPS_H
#define DET_SOFT_OPS_H
#include "det_soft.h"

#ifdef __METAL_VERSION__
#define DSO_FSQRT(a)   metal::precise::sqrt(a)
#define DSO_FDIV(a, b) metal::precise::divide((a), (b))
#define DSO_F2B(x) as_type<uint>(x)
#define DSO_B2F(b) as_type<float>(b)
#define DSO_CONST constant
#define DSO_TAB(T) constant T *
#else
#include <string.h>
#include <math.h>
#define DSO_FSQRT(a)   sqrtf(a)
#define DSO_FDIV(a, b) ((a) / (b))
DS_FN ds_u32 DSO_F2B(float x) { ds_u32 b; memcpy(&b, &x, 4); return b; }
DS_FN float  DSO_B2F(ds_u32 b) { float x; memcpy(&x, &b, 4); return x; }
#define DSO_CONST static const
#define DSO_TAB(T) const T *
#endif

// double constants (bit patterns)
#define DSO_ZERO 0x0000000000000000ull
#define DSO_HALF __HALF__
#define DSO_ONE  __ONE__
#define DSO_TWO  __TWO__
#define DSO_M2   __M2__
#define DSO_INV_LN2 __INV_LN2__
#define DSO_LN2_HI  __LN2_HI__
#define DSO_LN2_LO  __LN2_LO__
#define DSO_LN2     __LN2__
#define DSO_SQRT1_2 __SQRT1_2__
#define DSO_TWO_OVER_PI __TWO_OVER_PI__
#define DSO_PIO2_1 __PIO2_1__
#define DSO_PIO2_2 __PIO2_2__
#define DSO_PIO2_3 __PIO2_3__
#define DSO_TWENTY __TWENTY__
#define DSO_M_TWENTY __M_TWENTY__
#define DSO_INF 0x7FF0000000000000ull

// det_ldexp, mirrored literally (two-step scaling for large |k|)
DS_FN ds_u64 dso_ldexp(ds_u64 x, ds_i32 k) {
    if (k > 1023) {
        x = ds_mul(x, ((ds_u64) (1023 + 1023)) << 52); k -= 1023;
        if (k > 1023) { x = ds_mul(x, ((ds_u64) (1023 + 1023)) << 52); k -= 1023; if (k > 1023) k = 1023; }
    } else if (k < -1022) {
        x = ds_mul(x, ((ds_u64) (1023 - 1022)) << 52); k += 1022;
        if (k < -1022) { x = ds_mul(x, ((ds_u64) (1023 - 1022)) << 52); k += 1022; if (k < -1022) k = -1022; }
    }
    return ds_mul(x, ((ds_u64) (k + 1023)) << 52);
}

// e^r for |r| <= 0.36: Taylor to r^13
DS_FN ds_u64 dso_exp_small(ds_u64 r) {
    DSO_CONST ds_u64 c[14] = { __EXPC__ };
    ds_u64 p = c[13];
    for (int i = 12; i >= 0; i--) p = ds_add(ds_mul(p, r), c[i]);
    return p;
}
DS_FN ds_u64 dso_exp_d(ds_u64 x) {
    const ds_u64 k = ds_floor(ds_add(ds_mul(x, DSO_INV_LN2), DSO_HALF));
    const ds_u64 r = ds_sub(ds_sub(x, ds_mul(k, DSO_LN2_HI)), ds_mul(k, DSO_LN2_LO));
    return dso_ldexp(dso_exp_small(r), (ds_i32) ds_to_i64_trunc(k));
}
DS_FN ds_u32 dso_expf_bits(ds_u32 b) {                 // det_expf on float bits
    if (((b >> 23) & 0xFF) == 0xFF) return (b & 0x7FFFFF) ? b : ((b >> 31) ? 0u : b);
    const float x = DSO_B2F(b);
    if (x > 88.75f) return 0x7F800000u;
    if (x < -104.0f) return 0u;
    return ds_to_f32bits(dso_exp_d(ds_from_f32bits(b)));
}
DS_FN ds_u64 dso_exp2_d(ds_u64 y) {
    const ds_u64 k = ds_floor(ds_add(y, DSO_HALF));
    const ds_u64 r = ds_sub(y, k);
    return dso_ldexp(dso_exp_small(ds_mul(r, DSO_LN2)), (ds_i32) ds_to_i64_trunc(k));
}
// log2(x), finite normal x > 0
DS_FN ds_u64 dso_log2_d(ds_u64 x) {
    DSO_CONST ds_u64 invk[15] = { __INVK__ };            // 1/1, 1/3, ..., 1/29 as the reference divides them
    ds_i32 e = (ds_i32) ((x >> 52) & 0x7FF) - 1023;
    ds_u64 m = (x & 0xFFFFFFFFFFFFFull) | (1023ull << 52);
    if (ds_lt(DSO_SQRT1_2, m) && !ds_eq(DSO_SQRT1_2, m)) { m = ds_mul(m, DSO_HALF); e++; }   // m > sqrt(2)
    const ds_u64 s  = ds_div(ds_sub(m, DSO_ONE), ds_add(m, DSO_ONE));
    const ds_u64 s2 = ds_mul(s, s);
    ds_u64 p = DSO_ZERO;
    for (int k = 29; k >= 1; k -= 2) p = ds_add(ds_mul(p, s2), invk[(k - 1) / 2]);
    const ds_u64 ln_m = ds_mul(DSO_TWO, ds_mul(s, p));
    return ds_add(ds_from_i64(e), ds_mul(ln_m, DSO_INV_LN2));
}
// sin/cos after Cody-Waite reduction, Taylor
DS_FN void dso_sincos_d(ds_u64 x, DS_PTR(ds_u64) s, DS_PTR(ds_u64) c) {
    DSO_CONST ds_u64 sc[8] = { __SC__ };
    DSO_CONST ds_u64 cc[9] = { __CC__ };
    const ds_u64 n  = ds_floor(ds_add(ds_mul(x, DSO_TWO_OVER_PI), DSO_HALF));
    const ds_u64 r  = ds_sub(ds_sub(ds_sub(x, ds_mul(n, DSO_PIO2_1)), ds_mul(n, DSO_PIO2_2)), ds_mul(n, DSO_PIO2_3));
    const ds_u64 r2 = ds_mul(r, r);
    ds_u64 ps = sc[7];
    for (int i = 6; i >= 0; i--) ps = ds_add(ds_mul(ps, r2), sc[i]);
    ps = ds_mul(ps, r);
    ds_u64 pc = cc[8];
    for (int i = 7; i >= 0; i--) pc = ds_add(ds_mul(pc, r2), cc[i]);
    const ds_i64 q = ds_to_i64_trunc(n) & 3;
    switch (q) {
        case 0: *s = ps;          *c = pc;          break;
        case 1: *s = pc;          *c = ds_neg(ps);  break;
        case 2: *s = ds_neg(ps);  *c = ds_neg(pc);  break;
        default: *s = ds_neg(pc); *c = ps;          break;
    }
}
DS_FN void dso_sincosf_bits(ds_u32 theta, DS_PTR(ds_u32) s, DS_PTR(ds_u32) c) {
    ds_u64 sd, cd; dso_sincos_d(ds_from_f32bits(theta), &sd, &cd);
    *s = ds_to_f32bits(sd); *c = ds_to_f32bits(cd);
}
DS_FN ds_u64 dso_rope_freq(ds_i32 i, ds_i32 n_dims, ds_u32 freq_base) {
    const ds_u64 L = ds_mul(dso_log2_d(ds_from_f32bits(freq_base)), ds_div(ds_mul(DSO_M2, ds_from_i64(i)), ds_from_i64(n_dims)));
    return dso_exp2_d(L);
}
DS_FN void dso_rope_sincos(ds_u32 pos, ds_i32 i, ds_i32 n_dims, ds_u32 freq_base, ds_u32 freq_scale, DS_PTR(ds_u32) s, DS_PTR(ds_u32) c) {
    const ds_u64 theta = ds_mul(ds_mul(ds_from_f32bits(pos), dso_rope_freq(i, n_dims, freq_base)), ds_from_f32bits(freq_scale));
    ds_u64 sd, cd; dso_sincos_d(theta, &sd, &cd);
    *s = ds_to_f32bits(sd); *c = ds_to_f32bits(cd);
}
DS_FN void dso_rope_sincos_ff(ds_u32 pos, ds_i32 i, ds_i32 n_dims, ds_u32 freq_base, ds_u32 freq_scale, ds_u32 ff, DS_PTR(ds_u32) s, DS_PTR(ds_u32) c) {
    const ds_u64 theta = ds_mul(ds_div(ds_mul(ds_from_f32bits(pos), dso_rope_freq(i, n_dims, freq_base)), ds_from_f32bits(ff)), ds_from_f32bits(freq_scale));
    ds_u64 sd, cd; dso_sincos_d(theta, &sd, &cd);
    *s = ds_to_f32bits(sd); *c = ds_to_f32bits(cd);
}
DS_FN ds_u64 dso_tanh_d(ds_u64 y) {
    if (ds_lt(DSO_TWENTY, y)) return DSO_ONE;
    if (ds_lt(y, DSO_M_TWENTY)) return DSO_ONE | (1ull << 63);
    const ds_u64 u = dso_exp_d(ds_mul(DSO_TWO, y));
    return ds_div(ds_sub(u, DSO_ONE), ds_add(u, DSO_ONE));
}
DS_FN ds_u32 dso_tanhf_bits(ds_u32 b) {
    if (((b >> 23) & 0xFF) == 0xFF && (b & 0x7FFFFF)) return b;
    return ds_to_f32bits(dso_tanh_d(ds_from_f32bits(b)));
}
// float-domain formulas, the reference's operation order (float IEEE ops, no contraction)
#define DSO_GELU_COEF_A    0.044715f
#define DSO_SQRT_2_OVER_PI 0.79788456080286535587989211986876f
DS_FN float dso_geluf(float x) {
    const float inner = DSO_SQRT_2_OVER_PI * (x * (1.0f + (DSO_GELU_COEF_A * (x * x))));
    return (0.5f * x) * (1.0f + DSO_B2F(dso_tanhf_bits(DSO_F2B(inner))));
}
DS_FN float dso_sigmoidf(float x) { return DSO_FDIV(1.0f, 1.0f + DSO_B2F(dso_expf_bits(DSO_F2B(-x)))); }
DS_FN float dso_siluf(float x)    { return x * dso_sigmoidf(x); }

// ---- exact big accumulator (640-bit, radix 352): integer, shared with bp8_exact_soft's rule ----
#define DSO_BIG_LIMBS 20
#define DSO_BIG_RADIX 352
DS_FN void dso_big_zero(DS_PTR(ds_u32) acc) { for (int i = 0; i < DSO_BIG_LIMBS; i++) acc[i] = 0; }
// acc += v*v exactly from float bits; 0 for non-finite
DS_FN int dso_big_add_sq_bits(DS_PTR(ds_u32) acc, ds_u32 f) {
    if ((f & 0x7FFFFFFFu) == 0) return 1;
    const ds_i32 e = (f >> 23) & 0xFF; const ds_u64 mf = f & 0x7FFFFF;
    if (e == 0xFF) return 0;
    ds_u64 mant; ds_i32 e2;
    if (e == 0) { mant = mf; e2 = -149; } else { mant = mf | 0x800000ull; e2 = e - 127 - 23; }
    const ds_u64 P = mant * mant;
    const ds_i32 pos = 2 * e2 + DSO_BIG_RADIX;
    const ds_i32 w = pos >> 5, b = pos & 31;
    const ds_u64 lo = b ? (P << b) : P;
    const ds_u64 hi = b ? (P >> (64 - b)) : 0ull;
    ds_u32 parts[3]; parts[0] = (ds_u32) lo; parts[1] = (ds_u32) (lo >> 32); parts[2] = (ds_u32) hi;
    ds_u64 c = 0;
    for (int i = 0; i < 3; i++) { const ds_u64 t = (ds_u64) acc[w + i] + parts[i] + c; acc[w + i] = (ds_u32) t; c = t >> 32; }
    for (int i = w + 3; c && i < DSO_BIG_LIMBS; i++) { const ds_u64 t = (ds_u64) acc[i] + c; acc[i] = (ds_u32) t; c = t >> 32; }
    return 1;
}
// acc += v for a finite non-negative float (softmax numerators)
DS_FN void dso_big_add_f32_nonneg_bits(DS_PTR(ds_u32) acc, ds_u32 fb) {
    const ds_i32 e = (fb >> 23) & 0xFF, f = fb & 0x7FFFFF;
    if ((fb & 0x7FFFFFFFu) == 0 || e == 0xFF) return;
    ds_u64 mi; ds_i32 e2;
    if (e == 0) { mi = (ds_u64) f; e2 = -126 - 23; } else { mi = (ds_u64) (f | 0x800000); e2 = e - 127 - 23; }
    const ds_i32 pos = e2 + DSO_BIG_RADIX;
    const ds_i32 w = pos >> 5, b = pos & 31;
    const ds_u64 lo = b ? (mi << b) : mi;
    const ds_u64 hi = b ? (mi >> (64 - b)) : 0ull;
    ds_u32 parts[3]; parts[0] = (ds_u32) lo; parts[1] = (ds_u32) (lo >> 32); parts[2] = (ds_u32) hi;
    ds_u64 c = 0;
    for (int i = 0; i < 3; i++) { const ds_u64 t = (ds_u64) acc[w + i] + parts[i] + c; acc[w + i] = (ds_u32) t; c = t >> 32; }
    for (int i = w + 3; c && i < DSO_BIG_LIMBS; i++) { const ds_u64 t = (ds_u64) acc[i] + c; acc[i] = (ds_u32) t; c = t >> 32; }
}
DS_FN ds_i32 dso_big_top(BP8_CPTR_(ds_u32) acc) {
    for (int i = DSO_BIG_LIMBS - 1; i >= 0; i--) { if (acc[i]) { ds_i32 t = 31; while (!((acc[i] >> t) & 1u)) t--; return 32 * i + t; } }
    return -1;
}
DS_FN ds_u32 dso_big_bit(BP8_CPTR_(ds_u32) acc, ds_i32 j) { if (j < 0 || j >= 32 * DSO_BIG_LIMBS) return 0; return (acc[j >> 5] >> (j & 31)) & 1u; }
// correctly rounded double of S * 2^-RADIX
DS_FN ds_u64 dso_big_to_double(BP8_CPTR_(ds_u32) acc) {
    const ds_i32 t = dso_big_top(acc);
    if (t < 0) return DSO_ZERO;
    ds_u64 mant = 0;
    for (ds_i32 j = t; j > t - 53; j--) mant = (mant << 1) | dso_big_bit(acc, j);
    const ds_u32 guard = dso_big_bit(acc, t - 53);
    int sticky = 0;
    for (ds_i32 j = t - 54; j >= 0 && !sticky; j--) sticky |= dso_big_bit(acc, j);
    ds_i32 e = t - 52;
    if (guard && (sticky || (mant & 1u))) { mant++; if (mant == (1ull << 53)) { mant >>= 1; e++; } }
    return dso_ldexp(ds_from_i64((ds_i64) mant), e - DSO_BIG_RADIX);
}
// RMSNorm scale: mean = (float)(S/n); scale = 1/sqrtf(mean + eps)
DS_FN float dso_rms_scale(ds_u64 sumsq, ds_i32 n, float eps) {
    const float mean = DSO_B2F(ds_to_f32bits(ds_div(sumsq, ds_from_i64(n))));
    return DSO_FDIV(1.0f, DSO_FSQRT(mean + eps));
}
DS_FN float dso_soft_max_inv(ds_u64 sum) { return DSO_FDIV(1.0f, DSO_B2F(ds_to_f32bits(sum))); }
#endif
'''
reps = {'__HALF__': d(0.5), '__ONE__': d(1.0), '__TWO__': d(2.0), '__M2__': d(-2.0),
        '__INV_LN2__': d(1.44269504088896338700e+00), '__LN2_HI__': d(6.93147180369123816490e-01),
        '__LN2_LO__': d(1.90821492927058770002e-10), '__LN2__': d(6.93147180559945286227e-01),
        '__SQRT1_2__': d(1.41421356237309514547e+00), '__TWO_OVER_PI__': d(6.36619772367581382433e-01),
        '__PIO2_1__': d(1.57079632673412561417e+00), '__PIO2_2__': d(6.07710050650619224932e-11),
        '__PIO2_3__': d(2.02226624879595063154e-21), '__TWENTY__': d(20.0), '__M_TWENTY__': d(-20.0),
        '__EXPC__': ", ".join(d(v) for v in expc), '__SC__': ", ".join(d(v) for v in sc), '__CC__': ", ".join(d(v) for v in cc),
        '__INVK__': ", ".join(d(v) for v in inv_k)}
for k, v in reps.items(): out = out.replace(k, v)
out = out.replace('BP8_CPTR_(ds_u32)', 'const DS_PTR(ds_u32)'.replace('const thread', 'const thread') )
open('det_soft_ops.h', 'w').write(out)
print('wrote det_soft_ops.h')
